/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CheckoutRequest,
  CheckoutResponse,
  HTTPValidationError,
  PortalResponse,
  StripeWebhookApiV1BillingWebhookPost200,
  SubscriptionResponse
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Creates a Stripe Checkout Session for the tenant. Returns a URL to redirect the user to the Stripe-hosted checkout page. Requires tenant-admin role.
 * @summary Create Stripe checkout session
 */
export const createCheckoutSessionApiV1BillingCheckoutPost = (
    checkoutRequest: CheckoutRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CheckoutResponse>> => {
    
    
    return axios.post(
      `/api/v1/billing/checkout`,
      checkoutRequest,options
    );
  }



export const getCreateCheckoutSessionApiV1BillingCheckoutPostMutationOptions = <TError = AxiosError<void | HTTPValidationError | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>, TError,{data: CheckoutRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>, TError,{data: CheckoutRequest}, TContext> => {

const mutationKey = ['createCheckoutSessionApiV1BillingCheckoutPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>, {data: CheckoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCheckoutSessionApiV1BillingCheckoutPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCheckoutSessionApiV1BillingCheckoutPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>>
    export type CreateCheckoutSessionApiV1BillingCheckoutPostMutationBody = CheckoutRequest
    export type CreateCheckoutSessionApiV1BillingCheckoutPostMutationError = AxiosError<void | HTTPValidationError | void>

    /**
 * @summary Create Stripe checkout session
 */
export const useCreateCheckoutSessionApiV1BillingCheckoutPost = <TError = AxiosError<void | HTTPValidationError | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>, TError,{data: CheckoutRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>,
        TError,
        {data: CheckoutRequest},
        TContext
      > => {

      const mutationOptions = getCreateCheckoutSessionApiV1BillingCheckoutPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Returns the current subscription status for the tenant. Any authenticated user can check the subscription status.
 * @summary Get subscription status
 */
export const getSubscriptionStatusApiV1BillingSubscriptionGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubscriptionResponse>> => {
    
    
    return axios.get(
      `/api/v1/billing/subscription`,options
    );
  }




export const getGetSubscriptionStatusApiV1BillingSubscriptionGetQueryKey = () => {
    return [
    `/api/v1/billing/subscription`
    ] as const;
    }

    
export const getGetSubscriptionStatusApiV1BillingSubscriptionGetQueryOptions = <TData = Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSubscriptionStatusApiV1BillingSubscriptionGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>> = ({ signal }) => getSubscriptionStatusApiV1BillingSubscriptionGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSubscriptionStatusApiV1BillingSubscriptionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>>
export type GetSubscriptionStatusApiV1BillingSubscriptionGetQueryError = AxiosError<void>


/**
 * @summary Get subscription status
 */

export function useGetSubscriptionStatusApiV1BillingSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSubscriptionStatusApiV1BillingSubscriptionGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Creates a Stripe Billing Portal session for the tenant to manage their subscription, payment methods, and invoices. Requires tenant-admin role.
 * @summary Create Stripe billing portal session
 */
export const createPortalSessionApiV1BillingPortalPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PortalResponse>> => {
    
    
    return axios.post(
      `/api/v1/billing/portal`,undefined,options
    );
  }



export const getCreatePortalSessionApiV1BillingPortalPostMutationOptions = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>, TError,void, TContext> => {

const mutationKey = ['createPortalSessionApiV1BillingPortalPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>, void> = () => {
          

          return  createPortalSessionApiV1BillingPortalPost(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePortalSessionApiV1BillingPortalPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>>
    
    export type CreatePortalSessionApiV1BillingPortalPostMutationError = AxiosError<void | void>

    /**
 * @summary Create Stripe billing portal session
 */
export const useCreatePortalSessionApiV1BillingPortalPost = <TError = AxiosError<void | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreatePortalSessionApiV1BillingPortalPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Receives and processes Stripe webhook events. Validates the webhook signature using STRIPE_WEBHOOK_SECRET. This endpoint is public (no JWT required).
 * @summary Stripe webhook receiver
 */
export const stripeWebhookApiV1BillingWebhookPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StripeWebhookApiV1BillingWebhookPost200>> => {
    
    
    return axios.post(
      `/api/v1/billing/webhook`,undefined,options
    );
  }



export const getStripeWebhookApiV1BillingWebhookPostMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>, TError,void, TContext> => {

const mutationKey = ['stripeWebhookApiV1BillingWebhookPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>, void> = () => {
          

          return  stripeWebhookApiV1BillingWebhookPost(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StripeWebhookApiV1BillingWebhookPostMutationResult = NonNullable<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>>
    
    export type StripeWebhookApiV1BillingWebhookPostMutationError = AxiosError<void>

    /**
 * @summary Stripe webhook receiver
 */
export const useStripeWebhookApiV1BillingWebhookPost = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStripeWebhookApiV1BillingWebhookPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Billing Status
 */
export const getBillingStatusApiV1BillingStatusGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.get(
      `/api/v1/billing/status`,options
    );
  }




export const getGetBillingStatusApiV1BillingStatusGetQueryKey = () => {
    return [
    `/api/v1/billing/status`
    ] as const;
    }

    
export const getGetBillingStatusApiV1BillingStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBillingStatusApiV1BillingStatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>> = ({ signal }) => getBillingStatusApiV1BillingStatusGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetBillingStatusApiV1BillingStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>>
export type GetBillingStatusApiV1BillingStatusGetQueryError = AxiosError<unknown>


/**
 * @summary Get Billing Status
 */

export function useGetBillingStatusApiV1BillingStatusGet<TData = Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetBillingStatusApiV1BillingStatusGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



