/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppSchemasBillingSubscriptionResponse,
  CheckoutRequest,
  CheckoutResponse,
  CreditCheckoutRequest,
  HTTPValidationError,
  PortalResponse,
  ReconcileResponse,
  StripeWebhookApiV1BillingWebhookPost200,
  TrialResponse
} from '.././model';

import { customInstance } from '../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a Stripe Checkout Session for the tenant. Rejects if active subscription exists. Idempotent via request-scoped idempotency key. Requires tenant-admin role.
 * @summary Create Stripe checkout session
 */
export const createCheckoutSessionApiV1BillingCheckoutPost = (
    checkoutRequest: CheckoutRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CheckoutResponse>(
      {url: `/api/v1/billing/checkout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: checkoutRequest, signal
    },
      options);
    }
  


export const getCreateCheckoutSessionApiV1BillingCheckoutPostMutationOptions = <TError = void | HTTPValidationError | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>, TError,{data: CheckoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>, TError,{data: CheckoutRequest}, TContext> => {

const mutationKey = ['createCheckoutSessionApiV1BillingCheckoutPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>, {data: CheckoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCheckoutSessionApiV1BillingCheckoutPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCheckoutSessionApiV1BillingCheckoutPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>>
    export type CreateCheckoutSessionApiV1BillingCheckoutPostMutationBody = CheckoutRequest
    export type CreateCheckoutSessionApiV1BillingCheckoutPostMutationError = void | HTTPValidationError | void

    /**
 * @summary Create Stripe checkout session
 */
export const useCreateCheckoutSessionApiV1BillingCheckoutPost = <TError = void | HTTPValidationError | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>, TError,{data: CheckoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCheckoutSessionApiV1BillingCheckoutPost>>,
        TError,
        {data: CheckoutRequest},
        TContext
      > => {

      const mutationOptions = getCreateCheckoutSessionApiV1BillingCheckoutPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Creates a Stripe Checkout Session for buying specific credits top-ups. Independent of active subscriptions. Requires tenant-admin role.
 * @summary Create Stripe credit purchase checkout session
 */
export const createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost = (
    creditCheckoutRequest: CreditCheckoutRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CheckoutResponse>(
      {url: `/api/v1/billing/credits/checkout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: creditCheckoutRequest, signal
    },
      options);
    }
  


export const getCreateCreditCheckoutSessionApiV1BillingCreditsCheckoutPostMutationOptions = <TError = HTTPValidationError | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost>>, TError,{data: CreditCheckoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost>>, TError,{data: CreditCheckoutRequest}, TContext> => {

const mutationKey = ['createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost>>, {data: CreditCheckoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCreditCheckoutSessionApiV1BillingCreditsCheckoutPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost>>>
    export type CreateCreditCheckoutSessionApiV1BillingCreditsCheckoutPostMutationBody = CreditCheckoutRequest
    export type CreateCreditCheckoutSessionApiV1BillingCreditsCheckoutPostMutationError = HTTPValidationError | void

    /**
 * @summary Create Stripe credit purchase checkout session
 */
export const useCreateCreditCheckoutSessionApiV1BillingCreditsCheckoutPost = <TError = HTTPValidationError | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost>>, TError,{data: CreditCheckoutRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCreditCheckoutSessionApiV1BillingCreditsCheckoutPost>>,
        TError,
        {data: CreditCheckoutRequest},
        TContext
      > => {

      const mutationOptions = getCreateCreditCheckoutSessionApiV1BillingCreditsCheckoutPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Creates a Stripe 24-hour trial subscription. Rejects if: (a) trial already activated, or (b) active subscription exists. Requires tenant-admin role.
 * @summary Start a 24-hour free trial
 */
export const createTrialApiV1BillingTrialPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TrialResponse>(
      {url: `/api/v1/billing/trial`, method: 'POST', signal
    },
      options);
    }
  


export const getCreateTrialApiV1BillingTrialPostMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTrialApiV1BillingTrialPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createTrialApiV1BillingTrialPost>>, TError,void, TContext> => {

const mutationKey = ['createTrialApiV1BillingTrialPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTrialApiV1BillingTrialPost>>, void> = () => {
          

          return  createTrialApiV1BillingTrialPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTrialApiV1BillingTrialPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTrialApiV1BillingTrialPost>>>
    
    export type CreateTrialApiV1BillingTrialPostMutationError = void | void

    /**
 * @summary Start a 24-hour free trial
 */
export const useCreateTrialApiV1BillingTrialPost = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTrialApiV1BillingTrialPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createTrialApiV1BillingTrialPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateTrialApiV1BillingTrialPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Returns the current subscription status for the tenant. Any authenticated user can check the subscription status.
 * @summary Get subscription status
 */
export const getSubscriptionStatusApiV1BillingSubscriptionGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AppSchemasBillingSubscriptionResponse>(
      {url: `/api/v1/billing/subscription`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSubscriptionStatusApiV1BillingSubscriptionGetQueryKey = () => {
    return [
    `/api/v1/billing/subscription`
    ] as const;
    }

    
export const getGetSubscriptionStatusApiV1BillingSubscriptionGetQueryOptions = <TData = Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSubscriptionStatusApiV1BillingSubscriptionGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>> = ({ signal }) => getSubscriptionStatusApiV1BillingSubscriptionGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSubscriptionStatusApiV1BillingSubscriptionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>>
export type GetSubscriptionStatusApiV1BillingSubscriptionGetQueryError = void


/**
 * @summary Get subscription status
 */

export function useGetSubscriptionStatusApiV1BillingSubscriptionGet<TData = Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionStatusApiV1BillingSubscriptionGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSubscriptionStatusApiV1BillingSubscriptionGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Returns the current credit balance for the authenticated tenant.
 * @summary Get tenant credit balance
 */
export const getCreditBalanceApiV1BillingCreditsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/billing/credits`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCreditBalanceApiV1BillingCreditsGetQueryKey = () => {
    return [
    `/api/v1/billing/credits`
    ] as const;
    }

    
export const getGetCreditBalanceApiV1BillingCreditsGetQueryOptions = <TData = Awaited<ReturnType<typeof getCreditBalanceApiV1BillingCreditsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCreditBalanceApiV1BillingCreditsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCreditBalanceApiV1BillingCreditsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCreditBalanceApiV1BillingCreditsGet>>> = ({ signal }) => getCreditBalanceApiV1BillingCreditsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCreditBalanceApiV1BillingCreditsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCreditBalanceApiV1BillingCreditsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCreditBalanceApiV1BillingCreditsGet>>>
export type GetCreditBalanceApiV1BillingCreditsGetQueryError = unknown


/**
 * @summary Get tenant credit balance
 */

export function useGetCreditBalanceApiV1BillingCreditsGet<TData = Awaited<ReturnType<typeof getCreditBalanceApiV1BillingCreditsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCreditBalanceApiV1BillingCreditsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCreditBalanceApiV1BillingCreditsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Creates a Stripe Billing Portal session for the tenant to manage their subscription, payment methods, and invoices. Requires tenant-admin role.
 * @summary Create Stripe billing portal session
 */
export const createPortalSessionApiV1BillingPortalPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PortalResponse>(
      {url: `/api/v1/billing/portal`, method: 'POST', signal
    },
      options);
    }
  


export const getCreatePortalSessionApiV1BillingPortalPostMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>, TError,void, TContext> => {

const mutationKey = ['createPortalSessionApiV1BillingPortalPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>, void> = () => {
          

          return  createPortalSessionApiV1BillingPortalPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePortalSessionApiV1BillingPortalPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>>
    
    export type CreatePortalSessionApiV1BillingPortalPostMutationError = void | void

    /**
 * @summary Create Stripe billing portal session
 */
export const useCreatePortalSessionApiV1BillingPortalPost = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPortalSessionApiV1BillingPortalPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreatePortalSessionApiV1BillingPortalPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Receives and processes Stripe webhook events. Validates the webhook signature using STRIPE_WEBHOOK_SECRET. This endpoint is public (no JWT required).
 * @summary Stripe webhook receiver
 */
export const stripeWebhookApiV1BillingWebhookPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StripeWebhookApiV1BillingWebhookPost200>(
      {url: `/api/v1/billing/webhook`, method: 'POST', signal
    },
      options);
    }
  


export const getStripeWebhookApiV1BillingWebhookPostMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>, TError,void, TContext> => {

const mutationKey = ['stripeWebhookApiV1BillingWebhookPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>, void> = () => {
          

          return  stripeWebhookApiV1BillingWebhookPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StripeWebhookApiV1BillingWebhookPostMutationResult = NonNullable<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>>
    
    export type StripeWebhookApiV1BillingWebhookPostMutationError = void

    /**
 * @summary Stripe webhook receiver
 */
export const useStripeWebhookApiV1BillingWebhookPost = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof stripeWebhookApiV1BillingWebhookPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStripeWebhookApiV1BillingWebhookPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Force-syncs the tenant's local subscription record from Stripe's live state. Use this after completing a checkout when the webhook hasn't fired yet, or to fix null current_period_start / current_period_end values. Requires tenant-admin role.
 * @summary Reconcile subscription with Stripe
 */
export const reconcileSubscriptionApiV1BillingReconcilePost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ReconcileResponse>(
      {url: `/api/v1/billing/reconcile`, method: 'POST', signal
    },
      options);
    }
  


export const getReconcileSubscriptionApiV1BillingReconcilePostMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reconcileSubscriptionApiV1BillingReconcilePost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof reconcileSubscriptionApiV1BillingReconcilePost>>, TError,void, TContext> => {

const mutationKey = ['reconcileSubscriptionApiV1BillingReconcilePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reconcileSubscriptionApiV1BillingReconcilePost>>, void> = () => {
          

          return  reconcileSubscriptionApiV1BillingReconcilePost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReconcileSubscriptionApiV1BillingReconcilePostMutationResult = NonNullable<Awaited<ReturnType<typeof reconcileSubscriptionApiV1BillingReconcilePost>>>
    
    export type ReconcileSubscriptionApiV1BillingReconcilePostMutationError = void | void

    /**
 * @summary Reconcile subscription with Stripe
 */
export const useReconcileSubscriptionApiV1BillingReconcilePost = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reconcileSubscriptionApiV1BillingReconcilePost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof reconcileSubscriptionApiV1BillingReconcilePost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getReconcileSubscriptionApiV1BillingReconcilePostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Billing Status
 */
export const getBillingStatusApiV1BillingStatusGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/billing/status`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBillingStatusApiV1BillingStatusGetQueryKey = () => {
    return [
    `/api/v1/billing/status`
    ] as const;
    }

    
export const getGetBillingStatusApiV1BillingStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBillingStatusApiV1BillingStatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>> = ({ signal }) => getBillingStatusApiV1BillingStatusGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetBillingStatusApiV1BillingStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>>
export type GetBillingStatusApiV1BillingStatusGetQueryError = unknown


/**
 * @summary Get Billing Status
 */

export function useGetBillingStatusApiV1BillingStatusGet<TData = Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getBillingStatusApiV1BillingStatusGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetBillingStatusApiV1BillingStatusGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



