/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Superadmin Service
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddPermissionRequest,
  CreatePriceRequest,
  CreateProductRequest,
  EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody,
  GetAllInvoicesApiV1SuperadminInvoicesGetParams,
  GetAllPaymentsApiV1SuperadminPaymentsGetParams,
  GetAllSubscriptionsApiV1SuperadminSubscriptionsGetParams,
  GetAllTenantsApiV1SuperadminTenantsGetParams,
  HTTPValidationError,
  PermissionRegistryResponse,
  RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteParams
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Ensure Superadmin Exists
 */
export const ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost = (
    ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody: EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/ensure-superadmin-exists`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody, signal
    },
      options);
    }
  


export const getEnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost>>, TError,{data: EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost>>, TError,{data: EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody}, TContext> => {

const mutationKey = ['ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost>>, {data: EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody}> = (props) => {
          const {data} = props ?? {};

          return  ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostMutationResult = NonNullable<Awaited<ReturnType<typeof ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost>>>
    export type EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostMutationBody = EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody
    export type EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostMutationError = HTTPValidationError

    /**
 * @summary Ensure Superadmin Exists
 */
export const useEnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost>>, TError,{data: EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ensureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPost>>,
        TError,
        {data: EnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostBody},
        TContext
      > => {

      const mutationOptions = getEnsureSuperadminExistsApiV1SuperadminEnsureSuperadminExistsPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Enum Values
 */
export const getEnumValuesApiV1SuperadminEnumsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/enums`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEnumValuesApiV1SuperadminEnumsGetQueryKey = () => {
    return [
    `/api/v1/superadmin/enums`
    ] as const;
    }

    
export const getGetEnumValuesApiV1SuperadminEnumsGetQueryOptions = <TData = Awaited<ReturnType<typeof getEnumValuesApiV1SuperadminEnumsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumValuesApiV1SuperadminEnumsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumValuesApiV1SuperadminEnumsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnumValuesApiV1SuperadminEnumsGet>>> = ({ signal }) => getEnumValuesApiV1SuperadminEnumsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnumValuesApiV1SuperadminEnumsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumValuesApiV1SuperadminEnumsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEnumValuesApiV1SuperadminEnumsGet>>>
export type GetEnumValuesApiV1SuperadminEnumsGetQueryError = unknown


/**
 * @summary Get Enum Values
 */

export function useGetEnumValuesApiV1SuperadminEnumsGet<TData = Awaited<ReturnType<typeof getEnumValuesApiV1SuperadminEnumsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumValuesApiV1SuperadminEnumsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumValuesApiV1SuperadminEnumsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All Tenants
 */
export const getAllTenantsApiV1SuperadminTenantsGet = (
    params?: GetAllTenantsApiV1SuperadminTenantsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/tenants`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllTenantsApiV1SuperadminTenantsGetQueryKey = (params?: GetAllTenantsApiV1SuperadminTenantsGetParams,) => {
    return [
    `/api/v1/superadmin/tenants`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllTenantsApiV1SuperadminTenantsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllTenantsApiV1SuperadminTenantsGet>>, TError = HTTPValidationError>(params?: GetAllTenantsApiV1SuperadminTenantsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllTenantsApiV1SuperadminTenantsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTenantsApiV1SuperadminTenantsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTenantsApiV1SuperadminTenantsGet>>> = ({ signal }) => getAllTenantsApiV1SuperadminTenantsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTenantsApiV1SuperadminTenantsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllTenantsApiV1SuperadminTenantsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTenantsApiV1SuperadminTenantsGet>>>
export type GetAllTenantsApiV1SuperadminTenantsGetQueryError = HTTPValidationError


/**
 * @summary Get All Tenants
 */

export function useGetAllTenantsApiV1SuperadminTenantsGet<TData = Awaited<ReturnType<typeof getAllTenantsApiV1SuperadminTenantsGet>>, TError = HTTPValidationError>(
 params?: GetAllTenantsApiV1SuperadminTenantsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllTenantsApiV1SuperadminTenantsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllTenantsApiV1SuperadminTenantsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All Subscriptions
 */
export const getAllSubscriptionsApiV1SuperadminSubscriptionsGet = (
    params?: GetAllSubscriptionsApiV1SuperadminSubscriptionsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/subscriptions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllSubscriptionsApiV1SuperadminSubscriptionsGetQueryKey = (params?: GetAllSubscriptionsApiV1SuperadminSubscriptionsGetParams,) => {
    return [
    `/api/v1/superadmin/subscriptions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllSubscriptionsApiV1SuperadminSubscriptionsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllSubscriptionsApiV1SuperadminSubscriptionsGet>>, TError = HTTPValidationError>(params?: GetAllSubscriptionsApiV1SuperadminSubscriptionsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSubscriptionsApiV1SuperadminSubscriptionsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSubscriptionsApiV1SuperadminSubscriptionsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSubscriptionsApiV1SuperadminSubscriptionsGet>>> = ({ signal }) => getAllSubscriptionsApiV1SuperadminSubscriptionsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSubscriptionsApiV1SuperadminSubscriptionsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllSubscriptionsApiV1SuperadminSubscriptionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSubscriptionsApiV1SuperadminSubscriptionsGet>>>
export type GetAllSubscriptionsApiV1SuperadminSubscriptionsGetQueryError = HTTPValidationError


/**
 * @summary Get All Subscriptions
 */

export function useGetAllSubscriptionsApiV1SuperadminSubscriptionsGet<TData = Awaited<ReturnType<typeof getAllSubscriptionsApiV1SuperadminSubscriptionsGet>>, TError = HTTPValidationError>(
 params?: GetAllSubscriptionsApiV1SuperadminSubscriptionsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSubscriptionsApiV1SuperadminSubscriptionsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllSubscriptionsApiV1SuperadminSubscriptionsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All Payments
 */
export const getAllPaymentsApiV1SuperadminPaymentsGet = (
    params?: GetAllPaymentsApiV1SuperadminPaymentsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/payments`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllPaymentsApiV1SuperadminPaymentsGetQueryKey = (params?: GetAllPaymentsApiV1SuperadminPaymentsGetParams,) => {
    return [
    `/api/v1/superadmin/payments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllPaymentsApiV1SuperadminPaymentsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllPaymentsApiV1SuperadminPaymentsGet>>, TError = HTTPValidationError>(params?: GetAllPaymentsApiV1SuperadminPaymentsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPaymentsApiV1SuperadminPaymentsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllPaymentsApiV1SuperadminPaymentsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPaymentsApiV1SuperadminPaymentsGet>>> = ({ signal }) => getAllPaymentsApiV1SuperadminPaymentsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllPaymentsApiV1SuperadminPaymentsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllPaymentsApiV1SuperadminPaymentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPaymentsApiV1SuperadminPaymentsGet>>>
export type GetAllPaymentsApiV1SuperadminPaymentsGetQueryError = HTTPValidationError


/**
 * @summary Get All Payments
 */

export function useGetAllPaymentsApiV1SuperadminPaymentsGet<TData = Awaited<ReturnType<typeof getAllPaymentsApiV1SuperadminPaymentsGet>>, TError = HTTPValidationError>(
 params?: GetAllPaymentsApiV1SuperadminPaymentsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPaymentsApiV1SuperadminPaymentsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllPaymentsApiV1SuperadminPaymentsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All Invoices
 */
export const getAllInvoicesApiV1SuperadminInvoicesGet = (
    params?: GetAllInvoicesApiV1SuperadminInvoicesGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/invoices`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllInvoicesApiV1SuperadminInvoicesGetQueryKey = (params?: GetAllInvoicesApiV1SuperadminInvoicesGetParams,) => {
    return [
    `/api/v1/superadmin/invoices`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllInvoicesApiV1SuperadminInvoicesGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllInvoicesApiV1SuperadminInvoicesGet>>, TError = HTTPValidationError>(params?: GetAllInvoicesApiV1SuperadminInvoicesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllInvoicesApiV1SuperadminInvoicesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllInvoicesApiV1SuperadminInvoicesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllInvoicesApiV1SuperadminInvoicesGet>>> = ({ signal }) => getAllInvoicesApiV1SuperadminInvoicesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllInvoicesApiV1SuperadminInvoicesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllInvoicesApiV1SuperadminInvoicesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllInvoicesApiV1SuperadminInvoicesGet>>>
export type GetAllInvoicesApiV1SuperadminInvoicesGetQueryError = HTTPValidationError


/**
 * @summary Get All Invoices
 */

export function useGetAllInvoicesApiV1SuperadminInvoicesGet<TData = Awaited<ReturnType<typeof getAllInvoicesApiV1SuperadminInvoicesGet>>, TError = HTTPValidationError>(
 params?: GetAllInvoicesApiV1SuperadminInvoicesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllInvoicesApiV1SuperadminInvoicesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllInvoicesApiV1SuperadminInvoicesGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Tenant Billing
 */
export const getTenantBillingApiV1SuperadminTenantTenantIdBillingGet = (
    tenantId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/tenant/${tenantId}/billing`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTenantBillingApiV1SuperadminTenantTenantIdBillingGetQueryKey = (tenantId?: string,) => {
    return [
    `/api/v1/superadmin/tenant/${tenantId}/billing`
    ] as const;
    }

    
export const getGetTenantBillingApiV1SuperadminTenantTenantIdBillingGetQueryOptions = <TData = Awaited<ReturnType<typeof getTenantBillingApiV1SuperadminTenantTenantIdBillingGet>>, TError = HTTPValidationError>(tenantId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantBillingApiV1SuperadminTenantTenantIdBillingGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTenantBillingApiV1SuperadminTenantTenantIdBillingGetQueryKey(tenantId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTenantBillingApiV1SuperadminTenantTenantIdBillingGet>>> = ({ signal }) => getTenantBillingApiV1SuperadminTenantTenantIdBillingGet(tenantId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(tenantId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTenantBillingApiV1SuperadminTenantTenantIdBillingGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTenantBillingApiV1SuperadminTenantTenantIdBillingGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTenantBillingApiV1SuperadminTenantTenantIdBillingGet>>>
export type GetTenantBillingApiV1SuperadminTenantTenantIdBillingGetQueryError = HTTPValidationError


/**
 * @summary Get Tenant Billing
 */

export function useGetTenantBillingApiV1SuperadminTenantTenantIdBillingGet<TData = Awaited<ReturnType<typeof getTenantBillingApiV1SuperadminTenantTenantIdBillingGet>>, TError = HTTPValidationError>(
 tenantId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantBillingApiV1SuperadminTenantTenantIdBillingGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTenantBillingApiV1SuperadminTenantTenantIdBillingGetQueryOptions(tenantId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete Tenant
 */
export const deleteTenantApiV1SuperadminTenantTenantIdDelete = (
    tenantId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/tenant/${tenantId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTenantApiV1SuperadminTenantTenantIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTenantApiV1SuperadminTenantTenantIdDelete>>, TError,{tenantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTenantApiV1SuperadminTenantTenantIdDelete>>, TError,{tenantId: string}, TContext> => {

const mutationKey = ['deleteTenantApiV1SuperadminTenantTenantIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTenantApiV1SuperadminTenantTenantIdDelete>>, {tenantId: string}> = (props) => {
          const {tenantId} = props ?? {};

          return  deleteTenantApiV1SuperadminTenantTenantIdDelete(tenantId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTenantApiV1SuperadminTenantTenantIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTenantApiV1SuperadminTenantTenantIdDelete>>>
    
    export type DeleteTenantApiV1SuperadminTenantTenantIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Tenant
 */
export const useDeleteTenantApiV1SuperadminTenantTenantIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTenantApiV1SuperadminTenantTenantIdDelete>>, TError,{tenantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteTenantApiV1SuperadminTenantTenantIdDelete>>,
        TError,
        {tenantId: string},
        TContext
      > => {

      const mutationOptions = getDeleteTenantApiV1SuperadminTenantTenantIdDeleteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Create Product
 */
export const createProductApiV1SuperadminProductsPost = (
    createProductRequest: CreateProductRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProductRequest, signal
    },
      options);
    }
  


export const getCreateProductApiV1SuperadminProductsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductApiV1SuperadminProductsPost>>, TError,{data: CreateProductRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProductApiV1SuperadminProductsPost>>, TError,{data: CreateProductRequest}, TContext> => {

const mutationKey = ['createProductApiV1SuperadminProductsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProductApiV1SuperadminProductsPost>>, {data: CreateProductRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProductApiV1SuperadminProductsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProductApiV1SuperadminProductsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createProductApiV1SuperadminProductsPost>>>
    export type CreateProductApiV1SuperadminProductsPostMutationBody = CreateProductRequest
    export type CreateProductApiV1SuperadminProductsPostMutationError = HTTPValidationError

    /**
 * @summary Create Product
 */
export const useCreateProductApiV1SuperadminProductsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProductApiV1SuperadminProductsPost>>, TError,{data: CreateProductRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createProductApiV1SuperadminProductsPost>>,
        TError,
        {data: CreateProductRequest},
        TContext
      > => {

      const mutationOptions = getCreateProductApiV1SuperadminProductsPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Create Price
 */
export const createPriceApiV1SuperadminPricesPost = (
    createPriceRequest: CreatePriceRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/prices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPriceRequest, signal
    },
      options);
    }
  


export const getCreatePriceApiV1SuperadminPricesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPriceApiV1SuperadminPricesPost>>, TError,{data: CreatePriceRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPriceApiV1SuperadminPricesPost>>, TError,{data: CreatePriceRequest}, TContext> => {

const mutationKey = ['createPriceApiV1SuperadminPricesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPriceApiV1SuperadminPricesPost>>, {data: CreatePriceRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPriceApiV1SuperadminPricesPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePriceApiV1SuperadminPricesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPriceApiV1SuperadminPricesPost>>>
    export type CreatePriceApiV1SuperadminPricesPostMutationBody = CreatePriceRequest
    export type CreatePriceApiV1SuperadminPricesPostMutationError = HTTPValidationError

    /**
 * @summary Create Price
 */
export const useCreatePriceApiV1SuperadminPricesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPriceApiV1SuperadminPricesPost>>, TError,{data: CreatePriceRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPriceApiV1SuperadminPricesPost>>,
        TError,
        {data: CreatePriceRequest},
        TContext
      > => {

      const mutationOptions = getCreatePriceApiV1SuperadminPricesPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary List Plans
 */
export const listPlansApiV1SuperadminPlansGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/plans`, method: 'GET', signal
    },
      options);
    }
  



export const getListPlansApiV1SuperadminPlansGetQueryKey = () => {
    return [
    `/api/v1/superadmin/plans`
    ] as const;
    }

    
export const getListPlansApiV1SuperadminPlansGetQueryOptions = <TData = Awaited<ReturnType<typeof listPlansApiV1SuperadminPlansGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPlansApiV1SuperadminPlansGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPlansApiV1SuperadminPlansGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlansApiV1SuperadminPlansGet>>> = ({ signal }) => listPlansApiV1SuperadminPlansGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPlansApiV1SuperadminPlansGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPlansApiV1SuperadminPlansGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPlansApiV1SuperadminPlansGet>>>
export type ListPlansApiV1SuperadminPlansGetQueryError = unknown


/**
 * @summary List Plans
 */

export function useListPlansApiV1SuperadminPlansGet<TData = Awaited<ReturnType<typeof listPlansApiV1SuperadminPlansGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPlansApiV1SuperadminPlansGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPlansApiV1SuperadminPlansGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary List Role Permissions
 */
export const listRolePermissionsApiV1SuperadminRbacPermissionsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PermissionRegistryResponse[]>(
      {url: `/api/v1/superadmin/rbac/permissions`, method: 'GET', signal
    },
      options);
    }
  



export const getListRolePermissionsApiV1SuperadminRbacPermissionsGetQueryKey = () => {
    return [
    `/api/v1/superadmin/rbac/permissions`
    ] as const;
    }

    
export const getListRolePermissionsApiV1SuperadminRbacPermissionsGetQueryOptions = <TData = Awaited<ReturnType<typeof listRolePermissionsApiV1SuperadminRbacPermissionsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRolePermissionsApiV1SuperadminRbacPermissionsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRolePermissionsApiV1SuperadminRbacPermissionsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRolePermissionsApiV1SuperadminRbacPermissionsGet>>> = ({ signal }) => listRolePermissionsApiV1SuperadminRbacPermissionsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRolePermissionsApiV1SuperadminRbacPermissionsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRolePermissionsApiV1SuperadminRbacPermissionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRolePermissionsApiV1SuperadminRbacPermissionsGet>>>
export type ListRolePermissionsApiV1SuperadminRbacPermissionsGetQueryError = unknown


/**
 * @summary List Role Permissions
 */

export function useListRolePermissionsApiV1SuperadminRbacPermissionsGet<TData = Awaited<ReturnType<typeof listRolePermissionsApiV1SuperadminRbacPermissionsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRolePermissionsApiV1SuperadminRbacPermissionsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListRolePermissionsApiV1SuperadminRbacPermissionsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Add Role Permission
 */
export const addRolePermissionApiV1SuperadminRbacPermissionsPost = (
    addPermissionRequest: AddPermissionRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/rbac/permissions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addPermissionRequest, signal
    },
      options);
    }
  


export const getAddRolePermissionApiV1SuperadminRbacPermissionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addRolePermissionApiV1SuperadminRbacPermissionsPost>>, TError,{data: AddPermissionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addRolePermissionApiV1SuperadminRbacPermissionsPost>>, TError,{data: AddPermissionRequest}, TContext> => {

const mutationKey = ['addRolePermissionApiV1SuperadminRbacPermissionsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addRolePermissionApiV1SuperadminRbacPermissionsPost>>, {data: AddPermissionRequest}> = (props) => {
          const {data} = props ?? {};

          return  addRolePermissionApiV1SuperadminRbacPermissionsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddRolePermissionApiV1SuperadminRbacPermissionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof addRolePermissionApiV1SuperadminRbacPermissionsPost>>>
    export type AddRolePermissionApiV1SuperadminRbacPermissionsPostMutationBody = AddPermissionRequest
    export type AddRolePermissionApiV1SuperadminRbacPermissionsPostMutationError = HTTPValidationError

    /**
 * @summary Add Role Permission
 */
export const useAddRolePermissionApiV1SuperadminRbacPermissionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addRolePermissionApiV1SuperadminRbacPermissionsPost>>, TError,{data: AddPermissionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof addRolePermissionApiV1SuperadminRbacPermissionsPost>>,
        TError,
        {data: AddPermissionRequest},
        TContext
      > => {

      const mutationOptions = getAddRolePermissionApiV1SuperadminRbacPermissionsPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Remove Role Permission
 */
export const removeRolePermissionApiV1SuperadminRbacPermissionsDelete = (
    params: RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteParams,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/superadmin/rbac/permissions`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getRemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeRolePermissionApiV1SuperadminRbacPermissionsDelete>>, TError,{params: RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeRolePermissionApiV1SuperadminRbacPermissionsDelete>>, TError,{params: RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteParams}, TContext> => {

const mutationKey = ['removeRolePermissionApiV1SuperadminRbacPermissionsDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeRolePermissionApiV1SuperadminRbacPermissionsDelete>>, {params: RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteParams}> = (props) => {
          const {params} = props ?? {};

          return  removeRolePermissionApiV1SuperadminRbacPermissionsDelete(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeRolePermissionApiV1SuperadminRbacPermissionsDelete>>>
    
    export type RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteMutationError = HTTPValidationError

    /**
 * @summary Remove Role Permission
 */
export const useRemoveRolePermissionApiV1SuperadminRbacPermissionsDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeRolePermissionApiV1SuperadminRbacPermissionsDelete>>, TError,{params: RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof removeRolePermissionApiV1SuperadminRbacPermissionsDelete>>,
        TError,
        {params: RemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteParams},
        TContext
      > => {

      const mutationOptions = getRemoveRolePermissionApiV1SuperadminRbacPermissionsDeleteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    