/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetNotificationsApiV1NotificationsGetParams,
  HTTPValidationError,
  NotificationResponse,
  TokenResponse
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get notifications for the current user.
 * @summary Get Notifications
 */
export const getNotificationsApiV1NotificationsGet = (
    params?: GetNotificationsApiV1NotificationsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<NotificationResponse[]>(
      {url: `/api/v1/notifications`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetNotificationsApiV1NotificationsGetQueryKey = (params?: GetNotificationsApiV1NotificationsGetParams,) => {
    return [
    `/api/v1/notifications`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetNotificationsApiV1NotificationsGetQueryOptions = <TData = Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError = HTTPValidationError>(params?: GetNotificationsApiV1NotificationsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotificationsApiV1NotificationsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>> = ({ signal }) => getNotificationsApiV1NotificationsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNotificationsApiV1NotificationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>>
export type GetNotificationsApiV1NotificationsGetQueryError = HTTPValidationError


/**
 * @summary Get Notifications
 */

export function useGetNotificationsApiV1NotificationsGet<TData = Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError = HTTPValidationError>(
 params?: GetNotificationsApiV1NotificationsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNotificationsApiV1NotificationsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNotificationsApiV1NotificationsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Mark a notification as READ.
 * @summary Mark Notification Read
 */
export const markNotificationReadApiV1NotificationsNotificationIdReadPut = (
    notificationId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<NotificationResponse>(
      {url: `/api/v1/notifications/${notificationId}/read`, method: 'PUT'
    },
      options);
    }
  


export const getMarkNotificationReadApiV1NotificationsNotificationIdReadPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationReadApiV1NotificationsNotificationIdReadPut>>, TError,{notificationId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof markNotificationReadApiV1NotificationsNotificationIdReadPut>>, TError,{notificationId: string}, TContext> => {

const mutationKey = ['markNotificationReadApiV1NotificationsNotificationIdReadPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markNotificationReadApiV1NotificationsNotificationIdReadPut>>, {notificationId: string}> = (props) => {
          const {notificationId} = props ?? {};

          return  markNotificationReadApiV1NotificationsNotificationIdReadPut(notificationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarkNotificationReadApiV1NotificationsNotificationIdReadPutMutationResult = NonNullable<Awaited<ReturnType<typeof markNotificationReadApiV1NotificationsNotificationIdReadPut>>>
    
    export type MarkNotificationReadApiV1NotificationsNotificationIdReadPutMutationError = HTTPValidationError

    /**
 * @summary Mark Notification Read
 */
export const useMarkNotificationReadApiV1NotificationsNotificationIdReadPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationReadApiV1NotificationsNotificationIdReadPut>>, TError,{notificationId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof markNotificationReadApiV1NotificationsNotificationIdReadPut>>,
        TError,
        {notificationId: string},
        TContext
      > => {

      const mutationOptions = getMarkNotificationReadApiV1NotificationsNotificationIdReadPutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get the Web PubSub client access URL for the current user.
 * @summary Get Pubsub Token
 */
export const getPubsubTokenApiV1NotificationsTokenGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenResponse>(
      {url: `/api/v1/notifications/token`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPubsubTokenApiV1NotificationsTokenGetQueryKey = () => {
    return [
    `/api/v1/notifications/token`
    ] as const;
    }

    
export const getGetPubsubTokenApiV1NotificationsTokenGetQueryOptions = <TData = Awaited<ReturnType<typeof getPubsubTokenApiV1NotificationsTokenGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPubsubTokenApiV1NotificationsTokenGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPubsubTokenApiV1NotificationsTokenGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPubsubTokenApiV1NotificationsTokenGet>>> = ({ signal }) => getPubsubTokenApiV1NotificationsTokenGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPubsubTokenApiV1NotificationsTokenGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPubsubTokenApiV1NotificationsTokenGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPubsubTokenApiV1NotificationsTokenGet>>>
export type GetPubsubTokenApiV1NotificationsTokenGetQueryError = unknown


/**
 * @summary Get Pubsub Token
 */

export function useGetPubsubTokenApiV1NotificationsTokenGet<TData = Awaited<ReturnType<typeof getPubsubTokenApiV1NotificationsTokenGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPubsubTokenApiV1NotificationsTokenGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPubsubTokenApiV1NotificationsTokenGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



