/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

/**
 * Remaining hours of trial if trialing
 */
export type AppSchemasBillingSubscriptionResponseTrialRemainingHours = number | null;
