/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { AppSchemasSuperadminSubscriptionResponseTenantName } from './appSchemasSuperadminSubscriptionResponseTenantName';
import type { AppSchemasSuperadminSubscriptionResponseCurrentPeriodStart } from './appSchemasSuperadminSubscriptionResponseCurrentPeriodStart';
import type { AppSchemasSuperadminSubscriptionResponseCurrentPeriodEnd } from './appSchemasSuperadminSubscriptionResponseCurrentPeriodEnd';
import type { AppSchemasSuperadminSubscriptionResponseTrialEndsAt } from './appSchemasSuperadminSubscriptionResponseTrialEndsAt';

export interface AppSchemasSuperadminSubscriptionResponse {
  id: string;
  tenant_name?: AppSchemasSuperadminSubscriptionResponseTenantName;
  stripe_customer_id: string;
  stripe_subscription_id: string;
  status: string;
  plan: string;
  current_period_start?: AppSchemasSuperadminSubscriptionResponseCurrentPeriodStart;
  current_period_end?: AppSchemasSuperadminSubscriptionResponseCurrentPeriodEnd;
  trial_ends_at?: AppSchemasSuperadminSubscriptionResponseTrialEndsAt;
  created_at: string;
  updated_at: string;
}
