/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { AppSchemasBillingSubscriptionResponseStripeSubscriptionId } from './appSchemasBillingSubscriptionResponseStripeSubscriptionId';
import type { AppSchemasBillingSubscriptionResponseCurrentPeriodStart } from './appSchemasBillingSubscriptionResponseCurrentPeriodStart';
import type { AppSchemasBillingSubscriptionResponseCurrentPeriodEnd } from './appSchemasBillingSubscriptionResponseCurrentPeriodEnd';
import type { AppSchemasBillingSubscriptionResponseTrialRemainingHours } from './appSchemasBillingSubscriptionResponseTrialRemainingHours';

/**
 * Subscription status response.
 */
export interface AppSchemasBillingSubscriptionResponse {
  /** Subscription status: active, canceled, past_due, incomplete, trialing */
  status: string;
  /** Plan name / price nickname */
  plan: string;
  /** Stripe Subscription ID */
  stripe_subscription_id?: AppSchemasBillingSubscriptionResponseStripeSubscriptionId;
  /** Current billing period start */
  current_period_start?: AppSchemasBillingSubscriptionResponseCurrentPeriodStart;
  /** Current billing period end */
  current_period_end?: AppSchemasBillingSubscriptionResponseCurrentPeriodEnd;
  /** Remaining hours of trial if trialing */
  trial_remaining_hours?: AppSchemasBillingSubscriptionResponseTrialRemainingHours;
  /** Current credit balance for the tenant */
  credit_balance?: number;
}
