/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Tenant Onboarding
 * OpenAPI spec version: 0.1.0
 */
import type { AssignRoleRequestModelConfig } from './assignRoleRequestModelConfig';

export interface AssignRoleRequest {
  roles: string[];
  model_config?: AssignRoleRequestModelConfig;
}
