/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

export type BillingIntervalEnum = typeof BillingIntervalEnum[keyof typeof BillingIntervalEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BillingIntervalEnum = {
  month: 'month',
  year: 'year',
} as const;
