/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

/**
 * Allowed roles for bulk-invited employees (employee or manager only).
 */
export type BulkEmployeeRole = typeof BulkEmployeeRole[keyof typeof BulkEmployeeRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkEmployeeRole = {
  employee: 'employee',
  manager: 'manager',
} as const;
