/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Tenant Onboarding
 * OpenAPI spec version: 0.1.0
 */
import type { Employee } from './employee';

export interface BulkEmployeeRequest {
  organization_id: string;
  employees: Employee[];
}
