/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEmployeeEntry } from './bulkEmployeeEntry';

/**
 * Request body for POST /employees (bulk version).

Accepts up to 100 employees per call. Duplicate emails within
the request are automatically removed (case-insensitive).
The organization_id must match the tenant_id embedded in the
caller's Keycloak JWT — enforced in the service layer.
 */
export interface BulkEmployeeInviteRequest {
  /**
   * List of employees to onboard. Min 1, max 100 per request.
   * @minItems 1
   * @maxItems 100
   */
  employees: BulkEmployeeEntry[];
}
