/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEmployeeResult } from './bulkEmployeeResult';

/**
 * Response for POST /employees (bulk onboarding).

HTTP 207 Multi-Status — even when some employees fail, the request
as a whole succeeds with per-user results in 'created' / 'failed'.
 */
export interface BulkEmployeeResponse {
  organization_id: string;
  /** Employees successfully onboarded */
  created?: BulkEmployeeResult[];
  /** Employees that could not be onboarded, with error reasons */
  failed?: BulkEmployeeResult[];
  total_requested: number;
  total_created: number;
  total_failed: number;
}
