/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

/**
 * Delivery email address (optional). Required for non-gmail users. Must be gmail.com.
 */
export type BulkEmployeeEntryContactEmail = string | null;
