/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response containing the Stripe checkout URL.
 */
export interface CheckoutResponse {
  /** Redirect URL for the Stripe-hosted checkout page */
  checkout_url: string;
}
