/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { CouponResponseDiscountValue } from './couponResponseDiscountValue';
import type { CouponResponseFreeDaysAllocation } from './couponResponseFreeDaysAllocation';
import type { CouponResponseFreeCreditsAllocation } from './couponResponseFreeCreditsAllocation';
import type { CouponResponseStripePromoId } from './couponResponseStripePromoId';
import type { CouponResponseExpiresAt } from './couponResponseExpiresAt';

export interface CouponResponse {
  id: string;
  code: string;
  discount_type: string;
  discount_value: CouponResponseDiscountValue;
  free_days_allocation: CouponResponseFreeDaysAllocation;
  free_credits_allocation: CouponResponseFreeCreditsAllocation;
  stripe_promo_id: CouponResponseStripePromoId;
  expires_at: CouponResponseExpiresAt;
}
