/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { CouponCreateRequestExpiresInHours } from './couponCreateRequestExpiresInHours';
import type { CouponCreateRequestCurrency } from './couponCreateRequestCurrency';
import type { CouponCreateRequestProductId } from './couponCreateRequestProductId';
import type { CouponCreateRequestFreeDaysAllocation } from './couponCreateRequestFreeDaysAllocation';
import type { CouponCreateRequestFreeCreditsAllocation } from './couponCreateRequestFreeCreditsAllocation';

export interface CouponCreateRequest {
  /** A friendly name to identify the coupon (e.g., 'Summer Promo' or 'Onboarding 2026') */
  name: string;
  /** Number of hours until the coupon expires (e.g., 72) */
  expires_in_hours?: CouponCreateRequestExpiresInHours;
  /** 'percentage' or 'fixed_amount' */
  discount_type: string;
  /** The % off, or the fixed amount off */
  discount_value: number;
  /** Required if fixed_amount (e.g., 'inr', 'usd') */
  currency?: CouponCreateRequestCurrency;
  /** Stripe Product ID to restrict this coupon to */
  product_id?: CouponCreateRequestProductId;
  free_days_allocation?: CouponCreateRequestFreeDaysAllocation;
  free_credits_allocation?: CouponCreateRequestFreeCreditsAllocation;
}
