/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { BillingIntervalEnum } from './billingIntervalEnum';

/**
 * Billing interval — required when type is 'subscription'
 */
export type CreatePriceRequestInterval = BillingIntervalEnum | null;
