/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional label shown on Stripe invoices (e.g. 'Pro Monthly')
 */
export type CreatePriceRequestNickname = string | null;
