/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request body for creating a Stripe credit purchase checkout session.
 */
export interface CreditCheckoutRequest {
  /** Stripe Price ID for the credit package */
  price_id: string;
  /**
   * Amount of credits being purchased
   */
  credits: number;
}
