/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Tenant Onboarding
 * OpenAPI spec version: 0.1.0
 */

export interface Employee {
  email: string;
  first_name: string;
  last_name: string;
}
