/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { UserStatus } from './userStatus';

/**
 * Response after modifying employee status (disable/activate).
 */
export interface EmployeeStatusResponse {
  id: string;
  email: string;
  status: UserStatus;
  message: string;
}
