/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeResponse } from './employeeResponse';

/**
 * Paginated list of employees.
 */
export interface EmployeeListResponse {
  employees: EmployeeResponse[];
  /** Total number of employees matching the query */
  total: number;
  /**
   * Number of records skipped
   * @minimum 0
   */
  skip: number;
  /**
   * Maximum records returned
   * @minimum 1
   * @maximum 100
   */
  limit: number;
}
