/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

export interface EnumValuesResponse {
  tenant_statuses: string[];
  subscription_statuses: string[];
  migration_states: string[];
}
