/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { SubscriptionStatusEnum } from './subscriptionStatusEnum';

export type GetAllSubscriptionsSuperadminSubscriptionsGetParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
/**
 * Filter by subscription status
 */
status?: SubscriptionStatusEnum | null;
/**
 * Filter by plan name
 */
plan?: string | null;
};
