/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { TenantStatusEnum } from './tenantStatusEnum';

export type GetAllTenantsSuperadminTenantsGetParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
/**
 * Filter by tenant status
 */
status?: TenantStatusEnum | null;
/**
 * Search by tenant name or subdomain
 */
search?: string | null;
/**
 * Filter by SSO configuration status
 */
sso_configured?: boolean | null;
};
