/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

export type GetAllInvoicesSuperadminInvoicesGetParams = {
/**
 * Number of Stripe invoices to fetch
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
