/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

export type ListEmployeesApiV1EmployeesGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum records to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Filter by status: active, invited, disabled
 */
status?: string | null;
};
