/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { PriceResponseInterval } from './priceResponseInterval';
import type { PriceResponseIntervalCount } from './priceResponseIntervalCount';
import type { PriceResponseNickname } from './priceResponseNickname';
import type { PriceResponseMetadata } from './priceResponseMetadata';

/**
 * Individual price entry.
 */
export interface PriceResponse {
  price_id: string;
  amount: number;
  currency: string;
  interval?: PriceResponseInterval;
  interval_count?: PriceResponseIntervalCount;
  recurring: boolean;
  nickname?: PriceResponseNickname;
  metadata?: PriceResponseMetadata;
  active: boolean;
}
