/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

export type ProductTypeEnum = typeof ProductTypeEnum[keyof typeof ProductTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductTypeEnum = {
  subscription: 'subscription',
  credits: 'credits',
} as const;
