/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { ProductResponseDescription } from './productResponseDescription';
import type { ProductResponseMetadata } from './productResponseMetadata';
import type { ProductResponseCreated } from './productResponseCreated';

/**
 * Returned after creating a product.
 */
export interface ProductResponse {
  product_id: string;
  name: string;
  description?: ProductResponseDescription;
  type: string;
  metadata?: ProductResponseMetadata;
  active: boolean;
  created?: ProductResponseCreated;
}
