/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request to configure SSO for a tenant.
 */
export interface SSOConfigRequest {
  /** Identity provider vendor (e.g. 'azure_ad', 'okta', 'google', 'oidc') */
  provider_type?: string;
  sso_client_id: string;
  sso_client_secret: string;
  sso_issuer_url: string;
  sso_authorization_url: string;
  sso_token_url: string;
  sso_jwks_url: string;
}
