/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { SSOConfigUpdateRequestClientId } from './sSOConfigUpdateRequestClientId';
import type { SSOConfigUpdateRequestClientSecret } from './sSOConfigUpdateRequestClientSecret';
import type { SSOConfigUpdateRequestTenantId } from './sSOConfigUpdateRequestTenantId';

/**
 * Request to update SSO provider credentials and/or Azure AD tenant ID.
 */
export interface SSOConfigUpdateRequest {
  /** New Azure AD application (client) ID */
  client_id?: SSOConfigUpdateRequestClientId;
  /** New Azure AD client secret */
  client_secret?: SSOConfigUpdateRequestClientSecret;
  /** New Azure AD directory (tenant) ID. When provided, the four SSO URLs are automatically rebuilt. */
  tenant_id?: SSOConfigUpdateRequestTenantId;
}
