/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { SSOProviderInfoAuthorizationUrl } from './sSOProviderInfoAuthorizationUrl';
import type { SSOProviderInfoTokenUrl } from './sSOProviderInfoTokenUrl';
import type { SSOProviderInfoJwksUrl } from './sSOProviderInfoJwksUrl';

/**
 * Read-safe SSO provider details (no secret).
 */
export interface SSOProviderInfo {
  provider_type: string;
  client_id: string;
  issuer: string;
  authorization_url?: SSOProviderInfoAuthorizationUrl;
  token_url?: SSOProviderInfoTokenUrl;
  jwks_url?: SSOProviderInfoJwksUrl;
  client_secret?: string;
}
