/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { SubscriptionResponseTenantName } from './subscriptionResponseTenantName';
import type { SubscriptionResponseCurrentPeriodStart } from './subscriptionResponseCurrentPeriodStart';
import type { SubscriptionResponseCurrentPeriodEnd } from './subscriptionResponseCurrentPeriodEnd';
import type { SubscriptionResponseTrialEndsAt } from './subscriptionResponseTrialEndsAt';

export interface SubscriptionResponse {
  id: string;
  tenant_name?: SubscriptionResponseTenantName;
  stripe_customer_id: string;
  stripe_subscription_id: string;
  status: string;
  plan: string;
  current_period_start?: SubscriptionResponseCurrentPeriodStart;
  current_period_end?: SubscriptionResponseCurrentPeriodEnd;
  trial_ends_at?: SubscriptionResponseTrialEndsAt;
  created_at: string;
  updated_at: string;
}
