/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import type { TenantResponseContactEmail } from './tenantResponseContactEmail';
import type { TenantResponseStripeCustomerId } from './tenantResponseStripeCustomerId';
import type { TenantResponseTrialStartedAt } from './tenantResponseTrialStartedAt';
import type { TenantResponseTrialEndsAt } from './tenantResponseTrialEndsAt';
import type { TenantResponseTrialActivatedAt } from './tenantResponseTrialActivatedAt';

export interface TenantResponse {
  id: string;
  name: string;
  subdomain: string;
  schema_name: string;
  status: string;
  sso_configured: boolean;
  primary_email: string;
  contact_email?: TenantResponseContactEmail;
  stripe_customer_id?: TenantResponseStripeCustomerId;
  migration_state: string;
  trial_started_at?: TenantResponseTrialStartedAt;
  trial_ends_at?: TenantResponseTrialEndsAt;
  trial_activated_at?: TenantResponseTrialActivatedAt;
  trial_activated: boolean;
  created_at: string;
  updated_at: string;
}
