/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */

export type TenantStatusEnum = typeof TenantStatusEnum[keyof typeof TenantStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantStatusEnum = {
  trialing: 'trialing',
  active: 'active',
  past_due: 'past_due',
  expired: 'expired',
  paused: 'paused',
  pending: 'pending',
  cancelled: 'cancelled',
} as const;
