/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Candidate Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody,
  CandidateMeUploadSasApiV1CandidatesMeUploadSasPostBody,
  ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostBody,
  CreateCandidateApiV1CandidatesPostBody,
  GenerateMagicLinkApiV1CandidatesMagicLinkPostBody,
  GetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetParams,
  HTTPValidationError,
  ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody,
  ProcessCandidateApiV1CandidatesCandidateIdProcessPostParams,
  SaveCandidateMeApiV1CandidatesMePostBody,
  UpdateCandidateApiV1CandidatesCandidateIdPatchBody,
  UpdateCandidateMeApiV1CandidatesMePutBody,
  UploadSasApiV1CandidatesUploadSasPostBody
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Lightweight, unauthenticated endpoint to check candidate service health/warm-up.
 * @summary Health Check
 */
export const healthCheckApiV1CandidatesHealthGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/health`, method: 'GET', signal
    },
      options);
    }
  



export const getHealthCheckApiV1CandidatesHealthGetQueryKey = () => {
    return [
    `/api/v1/candidates/health`
    ] as const;
    }

    
export const getHealthCheckApiV1CandidatesHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthCheckApiV1CandidatesHealthGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1CandidatesHealthGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckApiV1CandidatesHealthGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheckApiV1CandidatesHealthGet>>> = ({ signal }) => healthCheckApiV1CandidatesHealthGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1CandidatesHealthGet>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckApiV1CandidatesHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheckApiV1CandidatesHealthGet>>>
export type HealthCheckApiV1CandidatesHealthGetQueryError = unknown


/**
 * @summary Health Check
 */

export function useHealthCheckApiV1CandidatesHealthGet<TData = Awaited<ReturnType<typeof healthCheckApiV1CandidatesHealthGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1CandidatesHealthGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckApiV1CandidatesHealthGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Candidates
 */
export const getCandidatesApiV1CandidatesGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCandidatesApiV1CandidatesGetQueryKey = () => {
    return [
    `/api/v1/candidates`
    ] as const;
    }

    
export const getGetCandidatesApiV1CandidatesGetQueryOptions = <TData = Awaited<ReturnType<typeof getCandidatesApiV1CandidatesGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidatesApiV1CandidatesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidatesApiV1CandidatesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCandidatesApiV1CandidatesGet>>> = ({ signal }) => getCandidatesApiV1CandidatesGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCandidatesApiV1CandidatesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCandidatesApiV1CandidatesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCandidatesApiV1CandidatesGet>>>
export type GetCandidatesApiV1CandidatesGetQueryError = unknown


/**
 * @summary Get Candidates
 */

export function useGetCandidatesApiV1CandidatesGet<TData = Awaited<ReturnType<typeof getCandidatesApiV1CandidatesGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidatesApiV1CandidatesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCandidatesApiV1CandidatesGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create Candidate
 */
export const createCandidateApiV1CandidatesPost = (
    createCandidateApiV1CandidatesPostBody: CreateCandidateApiV1CandidatesPostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCandidateApiV1CandidatesPostBody, signal
    },
      options);
    }
  


export const getCreateCandidateApiV1CandidatesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCandidateApiV1CandidatesPost>>, TError,{data: CreateCandidateApiV1CandidatesPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCandidateApiV1CandidatesPost>>, TError,{data: CreateCandidateApiV1CandidatesPostBody}, TContext> => {

const mutationKey = ['createCandidateApiV1CandidatesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCandidateApiV1CandidatesPost>>, {data: CreateCandidateApiV1CandidatesPostBody}> = (props) => {
          const {data} = props ?? {};

          return  createCandidateApiV1CandidatesPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCandidateApiV1CandidatesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createCandidateApiV1CandidatesPost>>>
    export type CreateCandidateApiV1CandidatesPostMutationBody = CreateCandidateApiV1CandidatesPostBody
    export type CreateCandidateApiV1CandidatesPostMutationError = HTTPValidationError

    /**
 * @summary Create Candidate
 */
export const useCreateCandidateApiV1CandidatesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCandidateApiV1CandidatesPost>>, TError,{data: CreateCandidateApiV1CandidatesPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createCandidateApiV1CandidatesPost>>,
        TError,
        {data: CreateCandidateApiV1CandidatesPostBody},
        TContext
      > => {

      const mutationOptions = getCreateCandidateApiV1CandidatesPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Upload Sas
 */
export const uploadSasApiV1CandidatesUploadSasPost = (
    uploadSasApiV1CandidatesUploadSasPostBody: UploadSasApiV1CandidatesUploadSasPostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/upload-sas`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadSasApiV1CandidatesUploadSasPostBody, signal
    },
      options);
    }
  


export const getUploadSasApiV1CandidatesUploadSasPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadSasApiV1CandidatesUploadSasPost>>, TError,{data: UploadSasApiV1CandidatesUploadSasPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadSasApiV1CandidatesUploadSasPost>>, TError,{data: UploadSasApiV1CandidatesUploadSasPostBody}, TContext> => {

const mutationKey = ['uploadSasApiV1CandidatesUploadSasPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadSasApiV1CandidatesUploadSasPost>>, {data: UploadSasApiV1CandidatesUploadSasPostBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadSasApiV1CandidatesUploadSasPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadSasApiV1CandidatesUploadSasPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadSasApiV1CandidatesUploadSasPost>>>
    export type UploadSasApiV1CandidatesUploadSasPostMutationBody = UploadSasApiV1CandidatesUploadSasPostBody
    export type UploadSasApiV1CandidatesUploadSasPostMutationError = HTTPValidationError

    /**
 * @summary Upload Sas
 */
export const useUploadSasApiV1CandidatesUploadSasPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadSasApiV1CandidatesUploadSasPost>>, TError,{data: UploadSasApiV1CandidatesUploadSasPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof uploadSasApiV1CandidatesUploadSasPost>>,
        TError,
        {data: UploadSasApiV1CandidatesUploadSasPostBody},
        TContext
      > => {

      const mutationOptions = getUploadSasApiV1CandidatesUploadSasPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Trigger resume processing for a candidate.
 * @summary Process Candidate
 */
export const processCandidateApiV1CandidatesCandidateIdProcessPost = (
    candidateId: number,
    processCandidateApiV1CandidatesCandidateIdProcessPostBody: ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody,
    params?: ProcessCandidateApiV1CandidatesCandidateIdProcessPostParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/${candidateId}/process`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: processCandidateApiV1CandidatesCandidateIdProcessPostBody,
        params, signal
    },
      options);
    }
  


export const getProcessCandidateApiV1CandidatesCandidateIdProcessPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processCandidateApiV1CandidatesCandidateIdProcessPost>>, TError,{candidateId: number;data: ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody;params?: ProcessCandidateApiV1CandidatesCandidateIdProcessPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof processCandidateApiV1CandidatesCandidateIdProcessPost>>, TError,{candidateId: number;data: ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody;params?: ProcessCandidateApiV1CandidatesCandidateIdProcessPostParams}, TContext> => {

const mutationKey = ['processCandidateApiV1CandidatesCandidateIdProcessPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processCandidateApiV1CandidatesCandidateIdProcessPost>>, {candidateId: number;data: ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody;params?: ProcessCandidateApiV1CandidatesCandidateIdProcessPostParams}> = (props) => {
          const {candidateId,data,params} = props ?? {};

          return  processCandidateApiV1CandidatesCandidateIdProcessPost(candidateId,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProcessCandidateApiV1CandidatesCandidateIdProcessPostMutationResult = NonNullable<Awaited<ReturnType<typeof processCandidateApiV1CandidatesCandidateIdProcessPost>>>
    export type ProcessCandidateApiV1CandidatesCandidateIdProcessPostMutationBody = ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody
    export type ProcessCandidateApiV1CandidatesCandidateIdProcessPostMutationError = HTTPValidationError

    /**
 * @summary Process Candidate
 */
export const useProcessCandidateApiV1CandidatesCandidateIdProcessPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processCandidateApiV1CandidatesCandidateIdProcessPost>>, TError,{candidateId: number;data: ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody;params?: ProcessCandidateApiV1CandidatesCandidateIdProcessPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof processCandidateApiV1CandidatesCandidateIdProcessPost>>,
        TError,
        {candidateId: number;data: ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody;params?: ProcessCandidateApiV1CandidatesCandidateIdProcessPostParams},
        TContext
      > => {

      const mutationOptions = getProcessCandidateApiV1CandidatesCandidateIdProcessPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Step 2: User approves the estimated cost from /process.
 * @summary Confirm Processing
 */
export const confirmProcessingApiV1CandidatesCandidateIdConfirmPost = (
    candidateId: number,
    confirmProcessingApiV1CandidatesCandidateIdConfirmPostBody: ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/${candidateId}/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confirmProcessingApiV1CandidatesCandidateIdConfirmPostBody, signal
    },
      options);
    }
  


export const getConfirmProcessingApiV1CandidatesCandidateIdConfirmPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmProcessingApiV1CandidatesCandidateIdConfirmPost>>, TError,{candidateId: number;data: ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmProcessingApiV1CandidatesCandidateIdConfirmPost>>, TError,{candidateId: number;data: ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostBody}, TContext> => {

const mutationKey = ['confirmProcessingApiV1CandidatesCandidateIdConfirmPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmProcessingApiV1CandidatesCandidateIdConfirmPost>>, {candidateId: number;data: ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostBody}> = (props) => {
          const {candidateId,data} = props ?? {};

          return  confirmProcessingApiV1CandidatesCandidateIdConfirmPost(candidateId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostMutationResult = NonNullable<Awaited<ReturnType<typeof confirmProcessingApiV1CandidatesCandidateIdConfirmPost>>>
    export type ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostMutationBody = ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostBody
    export type ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostMutationError = HTTPValidationError

    /**
 * @summary Confirm Processing
 */
export const useConfirmProcessingApiV1CandidatesCandidateIdConfirmPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmProcessingApiV1CandidatesCandidateIdConfirmPost>>, TError,{candidateId: number;data: ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof confirmProcessingApiV1CandidatesCandidateIdConfirmPost>>,
        TError,
        {candidateId: number;data: ConfirmProcessingApiV1CandidatesCandidateIdConfirmPostBody},
        TContext
      > => {

      const mutationOptions = getConfirmProcessingApiV1CandidatesCandidateIdConfirmPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Candidate Me
 */
export const getCandidateMeApiV1CandidatesMeGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCandidateMeApiV1CandidatesMeGetQueryKey = () => {
    return [
    `/api/v1/candidates/me`
    ] as const;
    }

    
export const getGetCandidateMeApiV1CandidatesMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getCandidateMeApiV1CandidatesMeGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidateMeApiV1CandidatesMeGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateMeApiV1CandidatesMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCandidateMeApiV1CandidatesMeGet>>> = ({ signal }) => getCandidateMeApiV1CandidatesMeGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCandidateMeApiV1CandidatesMeGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCandidateMeApiV1CandidatesMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCandidateMeApiV1CandidatesMeGet>>>
export type GetCandidateMeApiV1CandidatesMeGetQueryError = unknown


/**
 * @summary Get Candidate Me
 */

export function useGetCandidateMeApiV1CandidatesMeGet<TData = Awaited<ReturnType<typeof getCandidateMeApiV1CandidatesMeGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidateMeApiV1CandidatesMeGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCandidateMeApiV1CandidatesMeGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update Candidate Me
 */
export const updateCandidateMeApiV1CandidatesMePut = (
    updateCandidateMeApiV1CandidatesMePutBody: UpdateCandidateMeApiV1CandidatesMePutBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/me`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCandidateMeApiV1CandidatesMePutBody
    },
      options);
    }
  


export const getUpdateCandidateMeApiV1CandidatesMePutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCandidateMeApiV1CandidatesMePut>>, TError,{data: UpdateCandidateMeApiV1CandidatesMePutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCandidateMeApiV1CandidatesMePut>>, TError,{data: UpdateCandidateMeApiV1CandidatesMePutBody}, TContext> => {

const mutationKey = ['updateCandidateMeApiV1CandidatesMePut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCandidateMeApiV1CandidatesMePut>>, {data: UpdateCandidateMeApiV1CandidatesMePutBody}> = (props) => {
          const {data} = props ?? {};

          return  updateCandidateMeApiV1CandidatesMePut(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCandidateMeApiV1CandidatesMePutMutationResult = NonNullable<Awaited<ReturnType<typeof updateCandidateMeApiV1CandidatesMePut>>>
    export type UpdateCandidateMeApiV1CandidatesMePutMutationBody = UpdateCandidateMeApiV1CandidatesMePutBody
    export type UpdateCandidateMeApiV1CandidatesMePutMutationError = HTTPValidationError

    /**
 * @summary Update Candidate Me
 */
export const useUpdateCandidateMeApiV1CandidatesMePut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCandidateMeApiV1CandidatesMePut>>, TError,{data: UpdateCandidateMeApiV1CandidatesMePutBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateCandidateMeApiV1CandidatesMePut>>,
        TError,
        {data: UpdateCandidateMeApiV1CandidatesMePutBody},
        TContext
      > => {

      const mutationOptions = getUpdateCandidateMeApiV1CandidatesMePutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Save Candidate Me
 */
export const saveCandidateMeApiV1CandidatesMePost = (
    saveCandidateMeApiV1CandidatesMePostBody: SaveCandidateMeApiV1CandidatesMePostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/me`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: saveCandidateMeApiV1CandidatesMePostBody, signal
    },
      options);
    }
  


export const getSaveCandidateMeApiV1CandidatesMePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveCandidateMeApiV1CandidatesMePost>>, TError,{data: SaveCandidateMeApiV1CandidatesMePostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saveCandidateMeApiV1CandidatesMePost>>, TError,{data: SaveCandidateMeApiV1CandidatesMePostBody}, TContext> => {

const mutationKey = ['saveCandidateMeApiV1CandidatesMePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveCandidateMeApiV1CandidatesMePost>>, {data: SaveCandidateMeApiV1CandidatesMePostBody}> = (props) => {
          const {data} = props ?? {};

          return  saveCandidateMeApiV1CandidatesMePost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SaveCandidateMeApiV1CandidatesMePostMutationResult = NonNullable<Awaited<ReturnType<typeof saveCandidateMeApiV1CandidatesMePost>>>
    export type SaveCandidateMeApiV1CandidatesMePostMutationBody = SaveCandidateMeApiV1CandidatesMePostBody
    export type SaveCandidateMeApiV1CandidatesMePostMutationError = HTTPValidationError

    /**
 * @summary Save Candidate Me
 */
export const useSaveCandidateMeApiV1CandidatesMePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveCandidateMeApiV1CandidatesMePost>>, TError,{data: SaveCandidateMeApiV1CandidatesMePostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof saveCandidateMeApiV1CandidatesMePost>>,
        TError,
        {data: SaveCandidateMeApiV1CandidatesMePostBody},
        TContext
      > => {

      const mutationOptions = getSaveCandidateMeApiV1CandidatesMePostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Candidate
 */
export const getCandidateApiV1CandidatesCandidateIdGet = (
    candidateId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/${candidateId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCandidateApiV1CandidatesCandidateIdGetQueryKey = (candidateId?: number,) => {
    return [
    `/api/v1/candidates/${candidateId}`
    ] as const;
    }

    
export const getGetCandidateApiV1CandidatesCandidateIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getCandidateApiV1CandidatesCandidateIdGet>>, TError = HTTPValidationError>(candidateId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidateApiV1CandidatesCandidateIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateApiV1CandidatesCandidateIdGetQueryKey(candidateId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCandidateApiV1CandidatesCandidateIdGet>>> = ({ signal }) => getCandidateApiV1CandidatesCandidateIdGet(candidateId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(candidateId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCandidateApiV1CandidatesCandidateIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCandidateApiV1CandidatesCandidateIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCandidateApiV1CandidatesCandidateIdGet>>>
export type GetCandidateApiV1CandidatesCandidateIdGetQueryError = HTTPValidationError


/**
 * @summary Get Candidate
 */

export function useGetCandidateApiV1CandidatesCandidateIdGet<TData = Awaited<ReturnType<typeof getCandidateApiV1CandidatesCandidateIdGet>>, TError = HTTPValidationError>(
 candidateId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidateApiV1CandidatesCandidateIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCandidateApiV1CandidatesCandidateIdGetQueryOptions(candidateId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete Candidate
 */
export const deleteCandidateApiV1CandidatesCandidateIdDelete = (
    candidateId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/${candidateId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCandidateApiV1CandidatesCandidateIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCandidateApiV1CandidatesCandidateIdDelete>>, TError,{candidateId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCandidateApiV1CandidatesCandidateIdDelete>>, TError,{candidateId: number}, TContext> => {

const mutationKey = ['deleteCandidateApiV1CandidatesCandidateIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCandidateApiV1CandidatesCandidateIdDelete>>, {candidateId: number}> = (props) => {
          const {candidateId} = props ?? {};

          return  deleteCandidateApiV1CandidatesCandidateIdDelete(candidateId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCandidateApiV1CandidatesCandidateIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCandidateApiV1CandidatesCandidateIdDelete>>>
    
    export type DeleteCandidateApiV1CandidatesCandidateIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Candidate
 */
export const useDeleteCandidateApiV1CandidatesCandidateIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCandidateApiV1CandidatesCandidateIdDelete>>, TError,{candidateId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteCandidateApiV1CandidatesCandidateIdDelete>>,
        TError,
        {candidateId: number},
        TContext
      > => {

      const mutationOptions = getDeleteCandidateApiV1CandidatesCandidateIdDeleteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Update Candidate
 */
export const updateCandidateApiV1CandidatesCandidateIdPatch = (
    candidateId: number,
    updateCandidateApiV1CandidatesCandidateIdPatchBody: UpdateCandidateApiV1CandidatesCandidateIdPatchBody,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/${candidateId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateCandidateApiV1CandidatesCandidateIdPatchBody
    },
      options);
    }
  


export const getUpdateCandidateApiV1CandidatesCandidateIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCandidateApiV1CandidatesCandidateIdPatch>>, TError,{candidateId: number;data: UpdateCandidateApiV1CandidatesCandidateIdPatchBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCandidateApiV1CandidatesCandidateIdPatch>>, TError,{candidateId: number;data: UpdateCandidateApiV1CandidatesCandidateIdPatchBody}, TContext> => {

const mutationKey = ['updateCandidateApiV1CandidatesCandidateIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCandidateApiV1CandidatesCandidateIdPatch>>, {candidateId: number;data: UpdateCandidateApiV1CandidatesCandidateIdPatchBody}> = (props) => {
          const {candidateId,data} = props ?? {};

          return  updateCandidateApiV1CandidatesCandidateIdPatch(candidateId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCandidateApiV1CandidatesCandidateIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateCandidateApiV1CandidatesCandidateIdPatch>>>
    export type UpdateCandidateApiV1CandidatesCandidateIdPatchMutationBody = UpdateCandidateApiV1CandidatesCandidateIdPatchBody
    export type UpdateCandidateApiV1CandidatesCandidateIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Candidate
 */
export const useUpdateCandidateApiV1CandidatesCandidateIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCandidateApiV1CandidatesCandidateIdPatch>>, TError,{candidateId: number;data: UpdateCandidateApiV1CandidatesCandidateIdPatchBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateCandidateApiV1CandidatesCandidateIdPatch>>,
        TError,
        {candidateId: number;data: UpdateCandidateApiV1CandidatesCandidateIdPatchBody},
        TContext
      > => {

      const mutationOptions = getUpdateCandidateApiV1CandidatesCandidateIdPatchMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Download Sas
 */
export const getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet = (
    candidateId: number,
    params: GetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/${candidateId}/download-sas`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetQueryKey = (candidateId?: number,
    params?: GetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetParams,) => {
    return [
    `/api/v1/candidates/${candidateId}/download-sas`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetQueryOptions = <TData = Awaited<ReturnType<typeof getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet>>, TError = HTTPValidationError>(candidateId: number,
    params: GetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetQueryKey(candidateId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet>>> = ({ signal }) => getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet(candidateId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(candidateId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet>>>
export type GetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetQueryError = HTTPValidationError


/**
 * @summary Get Download Sas
 */

export function useGetDownloadSasApiV1CandidatesCandidateIdDownloadSasGet<TData = Awaited<ReturnType<typeof getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet>>, TError = HTTPValidationError>(
 candidateId: number,
    params: GetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDownloadSasApiV1CandidatesCandidateIdDownloadSasGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDownloadSasApiV1CandidatesCandidateIdDownloadSasGetQueryOptions(candidateId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Candidate Me Upload Sas
 */
export const candidateMeUploadSasApiV1CandidatesMeUploadSasPost = (
    candidateMeUploadSasApiV1CandidatesMeUploadSasPostBody: CandidateMeUploadSasApiV1CandidatesMeUploadSasPostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/me/upload-sas`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: candidateMeUploadSasApiV1CandidatesMeUploadSasPostBody, signal
    },
      options);
    }
  


export const getCandidateMeUploadSasApiV1CandidatesMeUploadSasPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof candidateMeUploadSasApiV1CandidatesMeUploadSasPost>>, TError,{data: CandidateMeUploadSasApiV1CandidatesMeUploadSasPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof candidateMeUploadSasApiV1CandidatesMeUploadSasPost>>, TError,{data: CandidateMeUploadSasApiV1CandidatesMeUploadSasPostBody}, TContext> => {

const mutationKey = ['candidateMeUploadSasApiV1CandidatesMeUploadSasPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof candidateMeUploadSasApiV1CandidatesMeUploadSasPost>>, {data: CandidateMeUploadSasApiV1CandidatesMeUploadSasPostBody}> = (props) => {
          const {data} = props ?? {};

          return  candidateMeUploadSasApiV1CandidatesMeUploadSasPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CandidateMeUploadSasApiV1CandidatesMeUploadSasPostMutationResult = NonNullable<Awaited<ReturnType<typeof candidateMeUploadSasApiV1CandidatesMeUploadSasPost>>>
    export type CandidateMeUploadSasApiV1CandidatesMeUploadSasPostMutationBody = CandidateMeUploadSasApiV1CandidatesMeUploadSasPostBody
    export type CandidateMeUploadSasApiV1CandidatesMeUploadSasPostMutationError = HTTPValidationError

    /**
 * @summary Candidate Me Upload Sas
 */
export const useCandidateMeUploadSasApiV1CandidatesMeUploadSasPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof candidateMeUploadSasApiV1CandidatesMeUploadSasPost>>, TError,{data: CandidateMeUploadSasApiV1CandidatesMeUploadSasPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof candidateMeUploadSasApiV1CandidatesMeUploadSasPost>>,
        TError,
        {data: CandidateMeUploadSasApiV1CandidatesMeUploadSasPostBody},
        TContext
      > => {

      const mutationOptions = getCandidateMeUploadSasApiV1CandidatesMeUploadSasPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Generate Magic Link
 */
export const generateMagicLinkApiV1CandidatesMagicLinkPost = (
    generateMagicLinkApiV1CandidatesMagicLinkPostBody: GenerateMagicLinkApiV1CandidatesMagicLinkPostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/magic-link`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateMagicLinkApiV1CandidatesMagicLinkPostBody, signal
    },
      options);
    }
  


export const getGenerateMagicLinkApiV1CandidatesMagicLinkPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateMagicLinkApiV1CandidatesMagicLinkPost>>, TError,{data: GenerateMagicLinkApiV1CandidatesMagicLinkPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof generateMagicLinkApiV1CandidatesMagicLinkPost>>, TError,{data: GenerateMagicLinkApiV1CandidatesMagicLinkPostBody}, TContext> => {

const mutationKey = ['generateMagicLinkApiV1CandidatesMagicLinkPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateMagicLinkApiV1CandidatesMagicLinkPost>>, {data: GenerateMagicLinkApiV1CandidatesMagicLinkPostBody}> = (props) => {
          const {data} = props ?? {};

          return  generateMagicLinkApiV1CandidatesMagicLinkPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateMagicLinkApiV1CandidatesMagicLinkPostMutationResult = NonNullable<Awaited<ReturnType<typeof generateMagicLinkApiV1CandidatesMagicLinkPost>>>
    export type GenerateMagicLinkApiV1CandidatesMagicLinkPostMutationBody = GenerateMagicLinkApiV1CandidatesMagicLinkPostBody
    export type GenerateMagicLinkApiV1CandidatesMagicLinkPostMutationError = HTTPValidationError

    /**
 * @summary Generate Magic Link
 */
export const useGenerateMagicLinkApiV1CandidatesMagicLinkPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateMagicLinkApiV1CandidatesMagicLinkPost>>, TError,{data: GenerateMagicLinkApiV1CandidatesMagicLinkPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof generateMagicLinkApiV1CandidatesMagicLinkPost>>,
        TError,
        {data: GenerateMagicLinkApiV1CandidatesMagicLinkPostBody},
        TContext
      > => {

      const mutationOptions = getGenerateMagicLinkApiV1CandidatesMagicLinkPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Slots By Magic Link
 */
export const getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet = (
    token: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/magic-link/${token}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGetQueryKey = (token?: string,) => {
    return [
    `/api/v1/candidates/magic-link/${token}`
    ] as const;
    }

    
export const getGetSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGetQueryOptions = <TData = Awaited<ReturnType<typeof getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet>>, TError = HTTPValidationError>(token: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGetQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet>>> = ({ signal }) => getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet(token, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet>>>
export type GetSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGetQueryError = HTTPValidationError


/**
 * @summary Get Slots By Magic Link
 */

export function useGetSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet<TData = Awaited<ReturnType<typeof getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet>>, TError = HTTPValidationError>(
 token: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSlotsByMagicLinkApiV1CandidatesMagicLinkTokenGetQueryOptions(token,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Book Slot By Magic Link
 */
export const bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost = (
    token: string,
    bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody: BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/magic-link/${token}/book`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody, signal
    },
      options);
    }
  


export const getBookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost>>, TError,{token: string;data: BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost>>, TError,{token: string;data: BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody}, TContext> => {

const mutationKey = ['bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost>>, {token: string;data: BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody}> = (props) => {
          const {token,data} = props ?? {};

          return  bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost(token,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostMutationResult = NonNullable<Awaited<ReturnType<typeof bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost>>>
    export type BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostMutationBody = BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody
    export type BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostMutationError = HTTPValidationError

    /**
 * @summary Book Slot By Magic Link
 */
export const useBookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost>>, TError,{token: string;data: BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPost>>,
        TError,
        {token: string;data: BookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody},
        TContext
      > => {

      const mutationOptions = getBookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    