/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApprovalActionRequest,
  HTTPValidationError,
  InitiateApprovalRequest
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Initiate an action that may require approval based on the config.
Normally called internally by other microservices, exposed here for end-to-end flow.
 * @summary Initiate Approval Request
 */
export const initiateApprovalRequestApiV1ApprovalsRequestPost = (
    initiateApprovalRequest: InitiateApprovalRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/approvals/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: initiateApprovalRequest, signal
    },
      options);
    }
  


export const getInitiateApprovalRequestApiV1ApprovalsRequestPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initiateApprovalRequestApiV1ApprovalsRequestPost>>, TError,{data: InitiateApprovalRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof initiateApprovalRequestApiV1ApprovalsRequestPost>>, TError,{data: InitiateApprovalRequest}, TContext> => {

const mutationKey = ['initiateApprovalRequestApiV1ApprovalsRequestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initiateApprovalRequestApiV1ApprovalsRequestPost>>, {data: InitiateApprovalRequest}> = (props) => {
          const {data} = props ?? {};

          return  initiateApprovalRequestApiV1ApprovalsRequestPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InitiateApprovalRequestApiV1ApprovalsRequestPostMutationResult = NonNullable<Awaited<ReturnType<typeof initiateApprovalRequestApiV1ApprovalsRequestPost>>>
    export type InitiateApprovalRequestApiV1ApprovalsRequestPostMutationBody = InitiateApprovalRequest
    export type InitiateApprovalRequestApiV1ApprovalsRequestPostMutationError = HTTPValidationError

    /**
 * @summary Initiate Approval Request
 */
export const useInitiateApprovalRequestApiV1ApprovalsRequestPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initiateApprovalRequestApiV1ApprovalsRequestPost>>, TError,{data: InitiateApprovalRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof initiateApprovalRequestApiV1ApprovalsRequestPost>>,
        TError,
        {data: InitiateApprovalRequest},
        TContext
      > => {

      const mutationOptions = getInitiateApprovalRequestApiV1ApprovalsRequestPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * List pending approval requests for the current user's role and tenant.
 * @summary Get Pending Approvals
 */
export const getPendingApprovalsApiV1ApprovalsPendingGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/approvals/pending`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPendingApprovalsApiV1ApprovalsPendingGetQueryKey = () => {
    return [
    `/api/v1/approvals/pending`
    ] as const;
    }

    
export const getGetPendingApprovalsApiV1ApprovalsPendingGetQueryOptions = <TData = Awaited<ReturnType<typeof getPendingApprovalsApiV1ApprovalsPendingGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalsApiV1ApprovalsPendingGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPendingApprovalsApiV1ApprovalsPendingGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPendingApprovalsApiV1ApprovalsPendingGet>>> = ({ signal }) => getPendingApprovalsApiV1ApprovalsPendingGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalsApiV1ApprovalsPendingGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPendingApprovalsApiV1ApprovalsPendingGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPendingApprovalsApiV1ApprovalsPendingGet>>>
export type GetPendingApprovalsApiV1ApprovalsPendingGetQueryError = unknown


/**
 * @summary Get Pending Approvals
 */

export function useGetPendingApprovalsApiV1ApprovalsPendingGet<TData = Awaited<ReturnType<typeof getPendingApprovalsApiV1ApprovalsPendingGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPendingApprovalsApiV1ApprovalsPendingGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPendingApprovalsApiV1ApprovalsPendingGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Approve a pending request. Emits APPROVAL_GRANTED to Service Bus.
 * @summary Approve Request
 */
export const approveRequestApiV1ApprovalsRequestIdApprovePost = (
    requestId: string,
    approvalActionRequest: ApprovalActionRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/approvals/${requestId}/approve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: approvalActionRequest, signal
    },
      options);
    }
  


export const getApproveRequestApiV1ApprovalsRequestIdApprovePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveRequestApiV1ApprovalsRequestIdApprovePost>>, TError,{requestId: string;data: ApprovalActionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof approveRequestApiV1ApprovalsRequestIdApprovePost>>, TError,{requestId: string;data: ApprovalActionRequest}, TContext> => {

const mutationKey = ['approveRequestApiV1ApprovalsRequestIdApprovePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveRequestApiV1ApprovalsRequestIdApprovePost>>, {requestId: string;data: ApprovalActionRequest}> = (props) => {
          const {requestId,data} = props ?? {};

          return  approveRequestApiV1ApprovalsRequestIdApprovePost(requestId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ApproveRequestApiV1ApprovalsRequestIdApprovePostMutationResult = NonNullable<Awaited<ReturnType<typeof approveRequestApiV1ApprovalsRequestIdApprovePost>>>
    export type ApproveRequestApiV1ApprovalsRequestIdApprovePostMutationBody = ApprovalActionRequest
    export type ApproveRequestApiV1ApprovalsRequestIdApprovePostMutationError = HTTPValidationError

    /**
 * @summary Approve Request
 */
export const useApproveRequestApiV1ApprovalsRequestIdApprovePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveRequestApiV1ApprovalsRequestIdApprovePost>>, TError,{requestId: string;data: ApprovalActionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof approveRequestApiV1ApprovalsRequestIdApprovePost>>,
        TError,
        {requestId: string;data: ApprovalActionRequest},
        TContext
      > => {

      const mutationOptions = getApproveRequestApiV1ApprovalsRequestIdApprovePostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Deny a pending request.
 * @summary Deny Request
 */
export const denyRequestApiV1ApprovalsRequestIdDenyPost = (
    requestId: string,
    approvalActionRequest: ApprovalActionRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/approvals/${requestId}/deny`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: approvalActionRequest, signal
    },
      options);
    }
  


export const getDenyRequestApiV1ApprovalsRequestIdDenyPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof denyRequestApiV1ApprovalsRequestIdDenyPost>>, TError,{requestId: string;data: ApprovalActionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof denyRequestApiV1ApprovalsRequestIdDenyPost>>, TError,{requestId: string;data: ApprovalActionRequest}, TContext> => {

const mutationKey = ['denyRequestApiV1ApprovalsRequestIdDenyPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof denyRequestApiV1ApprovalsRequestIdDenyPost>>, {requestId: string;data: ApprovalActionRequest}> = (props) => {
          const {requestId,data} = props ?? {};

          return  denyRequestApiV1ApprovalsRequestIdDenyPost(requestId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DenyRequestApiV1ApprovalsRequestIdDenyPostMutationResult = NonNullable<Awaited<ReturnType<typeof denyRequestApiV1ApprovalsRequestIdDenyPost>>>
    export type DenyRequestApiV1ApprovalsRequestIdDenyPostMutationBody = ApprovalActionRequest
    export type DenyRequestApiV1ApprovalsRequestIdDenyPostMutationError = HTTPValidationError

    /**
 * @summary Deny Request
 */
export const useDenyRequestApiV1ApprovalsRequestIdDenyPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof denyRequestApiV1ApprovalsRequestIdDenyPost>>, TError,{requestId: string;data: ApprovalActionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof denyRequestApiV1ApprovalsRequestIdDenyPost>>,
        TError,
        {requestId: string;data: ApprovalActionRequest},
        TContext
      > => {

      const mutationOptions = getDenyRequestApiV1ApprovalsRequestIdDenyPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * List requests initiated by the current user.
 * @summary Get My Requests
 */
export const getMyRequestsApiV1ApprovalsMyRequestsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/approvals/my-requests`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyRequestsApiV1ApprovalsMyRequestsGetQueryKey = () => {
    return [
    `/api/v1/approvals/my-requests`
    ] as const;
    }

    
export const getGetMyRequestsApiV1ApprovalsMyRequestsGetQueryOptions = <TData = Awaited<ReturnType<typeof getMyRequestsApiV1ApprovalsMyRequestsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyRequestsApiV1ApprovalsMyRequestsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyRequestsApiV1ApprovalsMyRequestsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyRequestsApiV1ApprovalsMyRequestsGet>>> = ({ signal }) => getMyRequestsApiV1ApprovalsMyRequestsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyRequestsApiV1ApprovalsMyRequestsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMyRequestsApiV1ApprovalsMyRequestsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMyRequestsApiV1ApprovalsMyRequestsGet>>>
export type GetMyRequestsApiV1ApprovalsMyRequestsGetQueryError = unknown


/**
 * @summary Get My Requests
 */

export function useGetMyRequestsApiV1ApprovalsMyRequestsGet<TData = Awaited<ReturnType<typeof getMyRequestsApiV1ApprovalsMyRequestsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyRequestsApiV1ApprovalsMyRequestsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMyRequestsApiV1ApprovalsMyRequestsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



