/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Resume Parsing Service
 * Heavy-lifting AI service for resume extraction and dossier generation
 * OpenAPI spec version: 1.0.0
 */

export type ProcessCandidateApiV1CandidatesCandidateIdProcessPostBody = { [key: string]: unknown };
