/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Resume Parsing Service
 * OpenAPI spec version: 1.0.0
 */

export type UploadSasCandidatesUploadSasPostBody = { [key: string]: unknown };
