/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Resume Parsing Service
 * Heavy-lifting AI service for resume extraction and dossier generation
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationErrorLocItem } from './validationErrorLocItem';
import type { ValidationErrorCtx } from './validationErrorCtx';

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}
