"use client";

import React, { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { format } from "date-fns";
import { Calendar, Clock, CheckCircle2, AlertCircle, RefreshCw } from "lucide-react";
import { toast } from "react-toastify";
import { useGetTenantBySubdomainApiV1TenantsBySubdomainSubdomainGet } from "@repo/orval-config/src/api/tenant/tenants/tenants";
// Interview Service hooks — magic links are generated by the interviews service
import {
  useGetSlotsByMagicLinkApiV1InterviewsMagicLinkTokenGet,
  useBookSlotByMagicLinkApiV1InterviewsMagicLinkTokenBookPost
} from "@repo/orval-config/src/api/interview/interviews/interviews";
import { Button } from "@repo/ui/components/ui/button";

export default function CandidateBookingPage() {
  const params = useParams();
  const token = params.token as string;
  const tenantSubdomain = params.tenant as string;

  const [selectedSlotId, setSelectedSlotId] = useState<number | null>(null);
  const [isBooked, setIsBooked] = useState(false);
  const [bookingDetails, setBookingDetails] = useState<any>(null);

  const [currentTime, setCurrentTime] = useState<Date | null>(null);

  useEffect(() => {
    setCurrentTime(new Date());
    const timer = setInterval(() => setCurrentTime(new Date()), 30000);
    return () => clearInterval(timer);
  }, []);

  // 1. Fetch Tenant details
  const { data: tenantDetails } = useGetTenantBySubdomainApiV1TenantsBySubdomainSubdomainGet(
    tenantSubdomain,
    {
      query: {
        enabled: !!tenantSubdomain,
      },
    } as any
  );

  const tenantDetailsAny = tenantDetails as any;
  const tenantId = tenantDetailsAny?.id || "";

  // 2. Fetch Slots & Interview Details
  const {
    data: magicLinkData,
    isLoading,
    isError,
    error,
  } = useGetSlotsByMagicLinkApiV1InterviewsMagicLinkTokenGet(token, {
    request: {
      headers: {
        "X-Tenant-Id": tenantId,
      },
    },
    query: {
      enabled: !!tenantId && !!token,
      retry: false,
    },
  } as any);

  const { interview, slots } = (magicLinkData as any) || {};

  // 3. Mutations
  const bookSlotMutation = useBookSlotByMagicLinkApiV1InterviewsMagicLinkTokenBookPost({
    request: {
      headers: {
        "X-Tenant-Id": tenantId,
      },
    },
  } as any);

  const handleBook = () => {
    if (!selectedSlotId) return;

    bookSlotMutation.mutate(
      {
        token: token,
        data: { slot_id: selectedSlotId },
      },
      {
        onSuccess: (data: any) => {
          setIsBooked(true);
          setBookingDetails(data);
          toast.success("Interview scheduled successfully!");
        },
        onError: (err: any) => {
          const detail = err?.response?.data?.detail || "Failed to book slot.";
          toast.error(detail);
        },
      }
    );
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-[#0a0a0a] text-white">
        <RefreshCw className="size-10 animate-spin text-primary mb-4" />
        <p className="text-muted-foreground font-medium">Retrieving slots...</p>
      </div>
    );
  }

  if (isError) {
    const errMsg = (error as any)?.response?.data?.detail || "Invalid or expired booking link.";
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0a0a0a] px-4">
        <div className="max-w-md w-full bg-card/40 backdrop-blur-xl border border-white/5 rounded-2xl p-8 text-center shadow-premium">
          <AlertCircle className="size-12 text-destructive mx-auto mb-4" />
          <h2 className="text-xl font-bold text-white mb-2">Access Error</h2>
          <p className="text-muted-foreground text-sm leading-relaxed mb-6">
            {errMsg}
          </p>
          <p className="text-xs text-muted-foreground">
            Please contact the recruitment coordinator for a new link.
          </p>
        </div>
      </div>
    );
  }

  // Active / booked verification state
  if (isBooked || (interview && interview.status === "BOOKED")) {
    const confirmedStart = bookingDetails?.scheduled_start || interview?.scheduled_start;
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0a0a0a] px-4">
        <div className="max-w-md w-full bg-card/40 backdrop-blur-xl border border-white/5 rounded-3xl p-8 text-center shadow-premium">
          <div className="size-16 rounded-2xl bg-success/10 flex items-center justify-center mx-auto mb-6">
            <CheckCircle2 className="size-8 text-success" />
          </div>
          <h2 className="text-2xl font-black text-white tracking-tight mb-2">Timing Confirmed!</h2>
          <p className="text-muted-foreground text-sm leading-relaxed mb-6">
            Your interview has been booked. You will receive an invitation email shortly.
          </p>
          {confirmedStart && (
            <div className="bg-white/5 border border-white/10 rounded-2xl p-4 text-left space-y-1 mb-6">
              <span className="text-xs font-bold text-muted-foreground block uppercase">Date & Time</span>
              <span className="text-base font-bold text-white block">
                {format(new Date(confirmedStart), "PPPP p")}
              </span>
            </div>
          )}
          <p className="text-xs text-muted-foreground">
            You can close this tab now.
          </p>
        </div>
      </div>
    );
  }

  const interviewSlots = Array.isArray(slots) ? slots : [];

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#0a0a0a] py-12 px-4">
      <div className="max-w-xl w-full bg-card border border-white/5 rounded-[2.5rem] shadow-premium overflow-hidden">
        {/* Header */}
        <div className="px-8 pt-8 pb-6 border-b border-white/5 flex gap-4 items-start bg-gradient-to-b from-white/[0.02] to-transparent">
          <div className="size-12 rounded-2xl bg-primary/10 flex items-center justify-center shrink-0">
            <Calendar className="size-6 text-primary" />
          </div>
          <div>
            <h2 className="text-2xl font-black text-white tracking-tight">
              {interview ? `Schedule: ${interview.title}` : "Select Interview Slot"}
            </h2>
            <p className="text-muted-foreground text-sm mt-1">
              {interview?.duration_minutes ? `Duration: ${interview.duration_minutes} minutes` : "Please select your preferred date & time."}
            </p>
          </div>
        </div>

        {/* Slot selection */}
        <div className="p-8">
          <div className="space-y-4 mb-6">
            <span className="text-xs font-bold text-muted-foreground uppercase tracking-widest block">
              Suggested Slots
            </span>

            {interviewSlots.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-h-[300px] overflow-y-auto pr-1">
                {interviewSlots.map((slot: any) => {
                  const startDate = new Date(slot.start_time || slot.start);
                  const isExpired = currentTime ? startDate < currentTime : false;
                  const isSelected = selectedSlotId === slot.id;
                  return (
                    <button
                      key={slot.id}
                      onClick={() => !isExpired && setSelectedSlotId(slot.id)}
                      disabled={isExpired}
                      title={isExpired ? "This slot has already passed" : ""}
                      className={`p-4 rounded-2xl border text-left flex flex-col transition-all ${
                        isExpired
                          ? "bg-white/5 border-white/10 opacity-70 cursor-not-allowed"
                          : isSelected
                          ? "bg-primary border-primary text-primary-foreground shadow-lg shadow-primary/20 scale-[1.01] cursor-pointer"
                          : "bg-white/5 border-white/5 hover:border-white/20 cursor-pointer"
                      }`}
                    >
                      <span className={`text-xs font-bold ${
                        isExpired ? "line-through text-muted-foreground" : "text-muted-foreground"
                      }`}>
                        {format(startDate, "EEEE, MMMM d")}
                      </span>
                      <span className={`text-sm font-bold mt-1 ${
                        isExpired ? "line-through text-white/50" : "text-white"
                      }`}>
                        {format(startDate, "p")}
                      </span>
                      {isExpired && (
                        <span className="text-[11px] text-destructive/90 font-bold mt-1.5 flex items-center gap-1">
                          <AlertCircle className="size-3" /> Slot expired
                        </span>
                      )}
                    </button>
                  );
                })}
              </div>
            ) : (
              <div className="text-center py-8 bg-white/5 rounded-2xl border border-dashed border-white/10">
                <p className="text-muted-foreground text-sm italic">
                  No available slots found. Please contact the recruitment coordinator for assistance.
                </p>
              </div>
            )}
          </div>

          <div className="pt-4 border-t border-white/5">
            <Button
              onClick={handleBook}
              disabled={!selectedSlotId || bookSlotMutation.isPending}
              className="w-full font-bold h-11"
            >
              {bookSlotMutation.isPending ? "Booking..." : "Confirm Selection"}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
