/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DetailedHealthResponse,
  HealthResponse
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns basic application health status for load balancers
 * @summary Basic health check
 */
export const healthCheckApiV1HealthGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<HealthResponse>(
      {url: `/api/v1/health`, method: 'GET', signal
    },
      options);
    }
  



export const getHealthCheckApiV1HealthGetQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }

    
export const getHealthCheckApiV1HealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckApiV1HealthGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>> = ({ signal }) => healthCheckApiV1HealthGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckApiV1HealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>>
export type HealthCheckApiV1HealthGetQueryError = unknown


/**
 * @summary Basic health check
 */

export function useHealthCheckApiV1HealthGet<TData = Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckApiV1HealthGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Returns detailed health status including database connectivity
 * @summary Detailed health check
 */
export const detailedHealthCheckApiV1HealthDetailedGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DetailedHealthResponse>(
      {url: `/api/v1/health/detailed`, method: 'GET', signal
    },
      options);
    }
  



export const getDetailedHealthCheckApiV1HealthDetailedGetQueryKey = () => {
    return [
    `/api/v1/health/detailed`
    ] as const;
    }

    
export const getDetailedHealthCheckApiV1HealthDetailedGetQueryOptions = <TData = Awaited<ReturnType<typeof detailedHealthCheckApiV1HealthDetailedGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof detailedHealthCheckApiV1HealthDetailedGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetailedHealthCheckApiV1HealthDetailedGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof detailedHealthCheckApiV1HealthDetailedGet>>> = ({ signal }) => detailedHealthCheckApiV1HealthDetailedGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detailedHealthCheckApiV1HealthDetailedGet>>, TError, TData> & { queryKey: QueryKey }
}

export type DetailedHealthCheckApiV1HealthDetailedGetQueryResult = NonNullable<Awaited<ReturnType<typeof detailedHealthCheckApiV1HealthDetailedGet>>>
export type DetailedHealthCheckApiV1HealthDetailedGetQueryError = unknown


/**
 * @summary Detailed health check
 */

export function useDetailedHealthCheckApiV1HealthDetailedGet<TData = Awaited<ReturnType<typeof detailedHealthCheckApiV1HealthDetailedGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof detailedHealthCheckApiV1HealthDetailedGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDetailedHealthCheckApiV1HealthDetailedGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Kubernetes readiness probe endpoint
 * @summary Readiness probe
 */
export const readinessCheckApiV1ReadinessGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/readiness`, method: 'GET', signal
    },
      options);
    }
  



export const getReadinessCheckApiV1ReadinessGetQueryKey = () => {
    return [
    `/api/v1/readiness`
    ] as const;
    }

    
export const getReadinessCheckApiV1ReadinessGetQueryOptions = <TData = Awaited<ReturnType<typeof readinessCheckApiV1ReadinessGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof readinessCheckApiV1ReadinessGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadinessCheckApiV1ReadinessGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof readinessCheckApiV1ReadinessGet>>> = ({ signal }) => readinessCheckApiV1ReadinessGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readinessCheckApiV1ReadinessGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ReadinessCheckApiV1ReadinessGetQueryResult = NonNullable<Awaited<ReturnType<typeof readinessCheckApiV1ReadinessGet>>>
export type ReadinessCheckApiV1ReadinessGetQueryError = unknown


/**
 * @summary Readiness probe
 */

export function useReadinessCheckApiV1ReadinessGet<TData = Awaited<ReturnType<typeof readinessCheckApiV1ReadinessGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof readinessCheckApiV1ReadinessGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReadinessCheckApiV1ReadinessGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Kubernetes liveness probe endpoint
 * @summary Liveness probe
 */
export const livenessCheckApiV1LivenessGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/liveness`, method: 'GET', signal
    },
      options);
    }
  



export const getLivenessCheckApiV1LivenessGetQueryKey = () => {
    return [
    `/api/v1/liveness`
    ] as const;
    }

    
export const getLivenessCheckApiV1LivenessGetQueryOptions = <TData = Awaited<ReturnType<typeof livenessCheckApiV1LivenessGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof livenessCheckApiV1LivenessGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLivenessCheckApiV1LivenessGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof livenessCheckApiV1LivenessGet>>> = ({ signal }) => livenessCheckApiV1LivenessGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof livenessCheckApiV1LivenessGet>>, TError, TData> & { queryKey: QueryKey }
}

export type LivenessCheckApiV1LivenessGetQueryResult = NonNullable<Awaited<ReturnType<typeof livenessCheckApiV1LivenessGet>>>
export type LivenessCheckApiV1LivenessGetQueryError = unknown


/**
 * @summary Liveness probe
 */

export function useLivenessCheckApiV1LivenessGet<TData = Awaited<ReturnType<typeof livenessCheckApiV1LivenessGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof livenessCheckApiV1LivenessGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLivenessCheckApiV1LivenessGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



