/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Job Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateJobApiV1JobsPostBody,
  HTTPValidationError
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Jobs
 */
export const getJobsApiV1JobsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/jobs`, method: 'GET', signal
    },
      options);
    }
  



export const getGetJobsApiV1JobsGetQueryKey = () => {
    return [
    `/api/v1/jobs`
    ] as const;
    }

    
export const getGetJobsApiV1JobsGetQueryOptions = <TData = Awaited<ReturnType<typeof getJobsApiV1JobsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getJobsApiV1JobsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobsApiV1JobsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobsApiV1JobsGet>>> = ({ signal }) => getJobsApiV1JobsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobsApiV1JobsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetJobsApiV1JobsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getJobsApiV1JobsGet>>>
export type GetJobsApiV1JobsGetQueryError = unknown


/**
 * @summary Get Jobs
 */

export function useGetJobsApiV1JobsGet<TData = Awaited<ReturnType<typeof getJobsApiV1JobsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getJobsApiV1JobsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetJobsApiV1JobsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create Job
 */
export const createJobApiV1JobsPost = (
    createJobApiV1JobsPostBody: CreateJobApiV1JobsPostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/jobs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createJobApiV1JobsPostBody, signal
    },
      options);
    }
  


export const getCreateJobApiV1JobsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobApiV1JobsPost>>, TError,{data: CreateJobApiV1JobsPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createJobApiV1JobsPost>>, TError,{data: CreateJobApiV1JobsPostBody}, TContext> => {

const mutationKey = ['createJobApiV1JobsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJobApiV1JobsPost>>, {data: CreateJobApiV1JobsPostBody}> = (props) => {
          const {data} = props ?? {};

          return  createJobApiV1JobsPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateJobApiV1JobsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createJobApiV1JobsPost>>>
    export type CreateJobApiV1JobsPostMutationBody = CreateJobApiV1JobsPostBody
    export type CreateJobApiV1JobsPostMutationError = HTTPValidationError

    /**
 * @summary Create Job
 */
export const useCreateJobApiV1JobsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJobApiV1JobsPost>>, TError,{data: CreateJobApiV1JobsPostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createJobApiV1JobsPost>>,
        TError,
        {data: CreateJobApiV1JobsPostBody},
        TContext
      > => {

      const mutationOptions = getCreateJobApiV1JobsPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Job
 */
export const getJobApiV1JobsJobIdGet = (
    jobId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/jobs/${jobId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetJobApiV1JobsJobIdGetQueryKey = (jobId?: number,) => {
    return [
    `/api/v1/jobs/${jobId}`
    ] as const;
    }

    
export const getGetJobApiV1JobsJobIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getJobApiV1JobsJobIdGet>>, TError = HTTPValidationError>(jobId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getJobApiV1JobsJobIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobApiV1JobsJobIdGetQueryKey(jobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobApiV1JobsJobIdGet>>> = ({ signal }) => getJobApiV1JobsJobIdGet(jobId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobApiV1JobsJobIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetJobApiV1JobsJobIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getJobApiV1JobsJobIdGet>>>
export type GetJobApiV1JobsJobIdGetQueryError = HTTPValidationError


/**
 * @summary Get Job
 */

export function useGetJobApiV1JobsJobIdGet<TData = Awaited<ReturnType<typeof getJobApiV1JobsJobIdGet>>, TError = HTTPValidationError>(
 jobId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getJobApiV1JobsJobIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetJobApiV1JobsJobIdGetQueryOptions(jobId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete Job
 */
export const deleteJobApiV1JobsJobIdDelete = (
    jobId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/jobs/${jobId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteJobApiV1JobsJobIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobApiV1JobsJobIdDelete>>, TError,{jobId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteJobApiV1JobsJobIdDelete>>, TError,{jobId: number}, TContext> => {

const mutationKey = ['deleteJobApiV1JobsJobIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteJobApiV1JobsJobIdDelete>>, {jobId: number}> = (props) => {
          const {jobId} = props ?? {};

          return  deleteJobApiV1JobsJobIdDelete(jobId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteJobApiV1JobsJobIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteJobApiV1JobsJobIdDelete>>>
    
    export type DeleteJobApiV1JobsJobIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Job
 */
export const useDeleteJobApiV1JobsJobIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteJobApiV1JobsJobIdDelete>>, TError,{jobId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteJobApiV1JobsJobIdDelete>>,
        TError,
        {jobId: number},
        TContext
      > => {

      const mutationOptions = getDeleteJobApiV1JobsJobIdDeleteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Job Evaluations
 */
export const getJobEvaluationsApiV1JobsJobIdEvaluationsGet = (
    jobId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/jobs/${jobId}/evaluations`, method: 'GET', signal
    },
      options);
    }
  



export const getGetJobEvaluationsApiV1JobsJobIdEvaluationsGetQueryKey = (jobId?: number,) => {
    return [
    `/api/v1/jobs/${jobId}/evaluations`
    ] as const;
    }

    
export const getGetJobEvaluationsApiV1JobsJobIdEvaluationsGetQueryOptions = <TData = Awaited<ReturnType<typeof getJobEvaluationsApiV1JobsJobIdEvaluationsGet>>, TError = HTTPValidationError>(jobId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getJobEvaluationsApiV1JobsJobIdEvaluationsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetJobEvaluationsApiV1JobsJobIdEvaluationsGetQueryKey(jobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobEvaluationsApiV1JobsJobIdEvaluationsGet>>> = ({ signal }) => getJobEvaluationsApiV1JobsJobIdEvaluationsGet(jobId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getJobEvaluationsApiV1JobsJobIdEvaluationsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetJobEvaluationsApiV1JobsJobIdEvaluationsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getJobEvaluationsApiV1JobsJobIdEvaluationsGet>>>
export type GetJobEvaluationsApiV1JobsJobIdEvaluationsGetQueryError = HTTPValidationError


/**
 * @summary Get Job Evaluations
 */

export function useGetJobEvaluationsApiV1JobsJobIdEvaluationsGet<TData = Awaited<ReturnType<typeof getJobEvaluationsApiV1JobsJobIdEvaluationsGet>>, TError = HTTPValidationError>(
 jobId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getJobEvaluationsApiV1JobsJobIdEvaluationsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetJobEvaluationsApiV1JobsJobIdEvaluationsGetQueryOptions(jobId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



