/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Tenant Onboarding
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AssignRoleRequest,
  AssignRoleResponse,
  BulkEmployeeRequest,
  HTTPValidationError,
  LoginRequest,
  SSOConfigRequest,
  TenantRequest
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary Onboard Tenant
 */
export const onboardTenantTenantsOnboardPost = (
    tenantRequest: TenantRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.post(
      `/tenants/onboard`,
      tenantRequest,options
    );
  }



export const getOnboardTenantTenantsOnboardPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardTenantTenantsOnboardPost>>, TError,{data: TenantRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof onboardTenantTenantsOnboardPost>>, TError,{data: TenantRequest}, TContext> => {

const mutationKey = ['onboardTenantTenantsOnboardPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof onboardTenantTenantsOnboardPost>>, {data: TenantRequest}> = (props) => {
          const {data} = props ?? {};

          return  onboardTenantTenantsOnboardPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OnboardTenantTenantsOnboardPostMutationResult = NonNullable<Awaited<ReturnType<typeof onboardTenantTenantsOnboardPost>>>
    export type OnboardTenantTenantsOnboardPostMutationBody = TenantRequest
    export type OnboardTenantTenantsOnboardPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Onboard Tenant
 */
export const useOnboardTenantTenantsOnboardPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardTenantTenantsOnboardPost>>, TError,{data: TenantRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof onboardTenantTenantsOnboardPost>>,
        TError,
        {data: TenantRequest},
        TContext
      > => {

      const mutationOptions = getOnboardTenantTenantsOnboardPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Setup Tenant Sso
 */
export const setupTenantSsoTenantsSsoSetupPost = (
    sSOConfigRequest: SSOConfigRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.post(
      `/tenants/sso/setup`,
      sSOConfigRequest,options
    );
  }



export const getSetupTenantSsoTenantsSsoSetupPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setupTenantSsoTenantsSsoSetupPost>>, TError,{data: SSOConfigRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof setupTenantSsoTenantsSsoSetupPost>>, TError,{data: SSOConfigRequest}, TContext> => {

const mutationKey = ['setupTenantSsoTenantsSsoSetupPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setupTenantSsoTenantsSsoSetupPost>>, {data: SSOConfigRequest}> = (props) => {
          const {data} = props ?? {};

          return  setupTenantSsoTenantsSsoSetupPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetupTenantSsoTenantsSsoSetupPostMutationResult = NonNullable<Awaited<ReturnType<typeof setupTenantSsoTenantsSsoSetupPost>>>
    export type SetupTenantSsoTenantsSsoSetupPostMutationBody = SSOConfigRequest
    export type SetupTenantSsoTenantsSsoSetupPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Setup Tenant Sso
 */
export const useSetupTenantSsoTenantsSsoSetupPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setupTenantSsoTenantsSsoSetupPost>>, TError,{data: SSOConfigRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof setupTenantSsoTenantsSsoSetupPost>>,
        TError,
        {data: SSOConfigRequest},
        TContext
      > => {

      const mutationOptions = getSetupTenantSsoTenantsSsoSetupPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Bulk Onboard Employees
 */
export const bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost = (
    bulkEmployeeRequest: BulkEmployeeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.post(
      `/tenants/employees/bulk-onboard`,
      bulkEmployeeRequest,options
    );
  }



export const getBulkOnboardEmployeesTenantsEmployeesBulkOnboardPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost>>, TError,{data: BulkEmployeeRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost>>, TError,{data: BulkEmployeeRequest}, TContext> => {

const mutationKey = ['bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost>>, {data: BulkEmployeeRequest}> = (props) => {
          const {data} = props ?? {};

          return  bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BulkOnboardEmployeesTenantsEmployeesBulkOnboardPostMutationResult = NonNullable<Awaited<ReturnType<typeof bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost>>>
    export type BulkOnboardEmployeesTenantsEmployeesBulkOnboardPostMutationBody = BulkEmployeeRequest
    export type BulkOnboardEmployeesTenantsEmployeesBulkOnboardPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Bulk Onboard Employees
 */
export const useBulkOnboardEmployeesTenantsEmployeesBulkOnboardPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost>>, TError,{data: BulkEmployeeRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof bulkOnboardEmployeesTenantsEmployeesBulkOnboardPost>>,
        TError,
        {data: BulkEmployeeRequest},
        TContext
      > => {

      const mutationOptions = getBulkOnboardEmployeesTenantsEmployeesBulkOnboardPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Assign one or more Keycloak **realm roles** to a user.

- **user_id** – the Keycloak UUID of the target user
- **roles**   – list of role names to assign (e.g. `["tenant-admin"]`)
 * @summary Assign realm roles to a user
 */
export const assignRoleToUserTenantsUsersUserIdRolesPost = (
    userId: string,
    assignRoleRequest: AssignRoleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssignRoleResponse>> => {
    
    
    return axios.post(
      `/tenants/users/${userId}/roles`,
      assignRoleRequest,options
    );
  }



export const getAssignRoleToUserTenantsUsersUserIdRolesPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUserTenantsUsersUserIdRolesPost>>, TError,{userId: string;data: AssignRoleRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUserTenantsUsersUserIdRolesPost>>, TError,{userId: string;data: AssignRoleRequest}, TContext> => {

const mutationKey = ['assignRoleToUserTenantsUsersUserIdRolesPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignRoleToUserTenantsUsersUserIdRolesPost>>, {userId: string;data: AssignRoleRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  assignRoleToUserTenantsUsersUserIdRolesPost(userId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AssignRoleToUserTenantsUsersUserIdRolesPostMutationResult = NonNullable<Awaited<ReturnType<typeof assignRoleToUserTenantsUsersUserIdRolesPost>>>
    export type AssignRoleToUserTenantsUsersUserIdRolesPostMutationBody = AssignRoleRequest
    export type AssignRoleToUserTenantsUsersUserIdRolesPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Assign realm roles to a user
 */
export const useAssignRoleToUserTenantsUsersUserIdRolesPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUserTenantsUsersUserIdRolesPost>>, TError,{userId: string;data: AssignRoleRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof assignRoleToUserTenantsUsersUserIdRolesPost>>,
        TError,
        {userId: string;data: AssignRoleRequest},
        TContext
      > => {

      const mutationOptions = getAssignRoleToUserTenantsUsersUserIdRolesPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Login
 */
export const loginAuthLoginPost = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.post(
      `/auth/login`,
      loginRequest,options
    );
  }



export const getLoginAuthLoginPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginAuthLoginPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAuthLoginPost>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginAuthLoginPost(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginAuthLoginPost>>>
    export type LoginAuthLoginPostMutationBody = LoginRequest
    export type LoginAuthLoginPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Login
 */
export const useLoginAuthLoginPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof loginAuthLoginPost>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginAuthLoginPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    