/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Interview Service
 * OpenAPI spec version: 1.0.0
 */

export type SaveCalendarConfigApiV1InterviewsCalendarConfigsPostBody = { [key: string]: unknown };
