/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */

export interface ChainStepInput {
  approver_role: string;
  timeout_hours?: number;
}
