/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */

export interface CreateDelegationRequest {
  delegate_user_id: string;
  delegate_role: string;
  starts_at: string;
  ends_at: string;
}
