/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */
import type { InitiateApprovalRequestPayload } from './initiateApprovalRequestPayload';
import type { InitiateApprovalRequestReason } from './initiateApprovalRequestReason';
import type { InitiateApprovalRequestManualApproverUserId } from './initiateApprovalRequestManualApproverUserId';

export interface InitiateApprovalRequest {
  permission_key: string;
  action_type: string;
  entity_type: string;
  entity_id: string;
  payload: InitiateApprovalRequestPayload;
  reason?: InitiateApprovalRequestReason;
  manual_approver_user_id?: InitiateApprovalRequestManualApproverUserId;
}
