/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */

export interface RolePermissionResponse {
  id: string;
  role_name: string;
  permission: string;
}
