/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */

export interface SSOConfigRequest {
  provider_type?: string;
  sso_client_id: string;
  sso_client_secret: string;
  sso_issuer_url: string;
  sso_authorization_url: string;
  sso_token_url: string;
  sso_jwks_url: string;
}
