/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */
import type { TenantRequestContactEmail } from './tenantRequestContactEmail';

export interface TenantRequest {
  email: string;
  tenant_name: string;
  contact_email?: TenantRequestContactEmail;
  enable_strict_workflows?: boolean;
}
