/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateApprovalRuleRequestMechanism } from './updateApprovalRuleRequestMechanism';
import type { UpdateApprovalRuleRequestApproverRole } from './updateApprovalRuleRequestApproverRole';
import type { UpdateApprovalRuleRequestApproverMode } from './updateApprovalRuleRequestApproverMode';
import type { UpdateApprovalRuleRequestDedicatedApproverUserId } from './updateApprovalRuleRequestDedicatedApproverUserId';
import type { UpdateApprovalRuleRequestManualAssignmentEnabled } from './updateApprovalRuleRequestManualAssignmentEnabled';
import type { UpdateApprovalRuleRequestChainSteps } from './updateApprovalRuleRequestChainSteps';
import type { UpdateApprovalRuleRequestTimeoutHours } from './updateApprovalRuleRequestTimeoutHours';
import type { UpdateApprovalRuleRequestTimeoutResolution } from './updateApprovalRuleRequestTimeoutResolution';
import type { UpdateApprovalRuleRequestSlaReminder1Hours } from './updateApprovalRuleRequestSlaReminder1Hours';
import type { UpdateApprovalRuleRequestSlaReminder2Hours } from './updateApprovalRuleRequestSlaReminder2Hours';
import type { UpdateApprovalRuleRequestSlaBreachHours } from './updateApprovalRuleRequestSlaBreachHours';
import type { UpdateApprovalRuleRequestAckWindowHours } from './updateApprovalRuleRequestAckWindowHours';
import type { UpdateApprovalRuleRequestNotifyLevel } from './updateApprovalRuleRequestNotifyLevel';
import type { UpdateApprovalRuleRequestDescription } from './updateApprovalRuleRequestDescription';

export interface UpdateApprovalRuleRequest {
  mechanism?: UpdateApprovalRuleRequestMechanism;
  approver_role?: UpdateApprovalRuleRequestApproverRole;
  approver_mode?: UpdateApprovalRuleRequestApproverMode;
  dedicated_approver_user_id?: UpdateApprovalRuleRequestDedicatedApproverUserId;
  manual_assignment_enabled?: UpdateApprovalRuleRequestManualAssignmentEnabled;
  chain_steps?: UpdateApprovalRuleRequestChainSteps;
  timeout_hours?: UpdateApprovalRuleRequestTimeoutHours;
  timeout_resolution?: UpdateApprovalRuleRequestTimeoutResolution;
  sla_reminder_1_hours?: UpdateApprovalRuleRequestSlaReminder1Hours;
  sla_reminder_2_hours?: UpdateApprovalRuleRequestSlaReminder2Hours;
  sla_breach_hours?: UpdateApprovalRuleRequestSlaBreachHours;
  ack_window_hours?: UpdateApprovalRuleRequestAckWindowHours;
  notify_level?: UpdateApprovalRuleRequestNotifyLevel;
  description?: UpdateApprovalRuleRequestDescription;
  confirm_hierarchy_warning?: boolean;
  confirm_auto_approve_warning?: boolean;
}
