/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */
import type { UserPermissionResponseGrantedBy } from './userPermissionResponseGrantedBy';

export interface UserPermissionResponse {
  id: string;
  tenant_id: string;
  user_id: string;
  permission: string;
  granted_by: UserPermissionResponseGrantedBy;
}
