/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Media Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Start recording for an interview slot.

Called by Interview Service when both candidate and interviewer are present.

Request body:
    {
        "interview_id": int,
        "slot_id": int,
        "room_name": str,
        "tenant_id": str  (required — passed from interview-service)
    }
 * @summary Start Recording
 */
export const startRecordingApiV1RecordingsStartPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/recordings/start`, method: 'POST', signal
    },
      options);
    }
  


export const getStartRecordingApiV1RecordingsStartPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRecordingApiV1RecordingsStartPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startRecordingApiV1RecordingsStartPost>>, TError,void, TContext> => {

const mutationKey = ['startRecordingApiV1RecordingsStartPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startRecordingApiV1RecordingsStartPost>>, void> = () => {
          

          return  startRecordingApiV1RecordingsStartPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartRecordingApiV1RecordingsStartPostMutationResult = NonNullable<Awaited<ReturnType<typeof startRecordingApiV1RecordingsStartPost>>>
    
    export type StartRecordingApiV1RecordingsStartPostMutationError = unknown

    /**
 * @summary Start Recording
 */
export const useStartRecordingApiV1RecordingsStartPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRecordingApiV1RecordingsStartPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof startRecordingApiV1RecordingsStartPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStartRecordingApiV1RecordingsStartPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Stop recording for an interview slot.

Called by Interview Service when participants leave the room.

Request body:
    {
        "slot_id": int,
        "tenant_id": str
    }
OR:
    {
        "egress_id": str,
        "tenant_id": str
    }
 * @summary Stop Recording
 */
export const stopRecordingApiV1RecordingsStopPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/recordings/stop`, method: 'POST', signal
    },
      options);
    }
  


export const getStopRecordingApiV1RecordingsStopPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopRecordingApiV1RecordingsStopPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stopRecordingApiV1RecordingsStopPost>>, TError,void, TContext> => {

const mutationKey = ['stopRecordingApiV1RecordingsStopPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stopRecordingApiV1RecordingsStopPost>>, void> = () => {
          

          return  stopRecordingApiV1RecordingsStopPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StopRecordingApiV1RecordingsStopPostMutationResult = NonNullable<Awaited<ReturnType<typeof stopRecordingApiV1RecordingsStopPost>>>
    
    export type StopRecordingApiV1RecordingsStopPostMutationError = unknown

    /**
 * @summary Stop Recording
 */
export const useStopRecordingApiV1RecordingsStopPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopRecordingApiV1RecordingsStopPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof stopRecordingApiV1RecordingsStopPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStopRecordingApiV1RecordingsStopPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get the current recording status for a slot.

Query params:
    tenant_id: str (required)
 * @summary Get Recording Status
 */
export const getRecordingStatusApiV1RecordingsSlotIdStatusGet = (
    slotId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/recordings/${slotId}/status`, method: 'GET', signal
    },
      options);
    }
  



export const getGetRecordingStatusApiV1RecordingsSlotIdStatusGetQueryKey = (slotId?: number,) => {
    return [
    `/api/v1/recordings/${slotId}/status`
    ] as const;
    }

    
export const getGetRecordingStatusApiV1RecordingsSlotIdStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getRecordingStatusApiV1RecordingsSlotIdStatusGet>>, TError = HTTPValidationError>(slotId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecordingStatusApiV1RecordingsSlotIdStatusGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecordingStatusApiV1RecordingsSlotIdStatusGetQueryKey(slotId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecordingStatusApiV1RecordingsSlotIdStatusGet>>> = ({ signal }) => getRecordingStatusApiV1RecordingsSlotIdStatusGet(slotId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(slotId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecordingStatusApiV1RecordingsSlotIdStatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecordingStatusApiV1RecordingsSlotIdStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRecordingStatusApiV1RecordingsSlotIdStatusGet>>>
export type GetRecordingStatusApiV1RecordingsSlotIdStatusGetQueryError = HTTPValidationError


/**
 * @summary Get Recording Status
 */

export function useGetRecordingStatusApiV1RecordingsSlotIdStatusGet<TData = Awaited<ReturnType<typeof getRecordingStatusApiV1RecordingsSlotIdStatusGet>>, TError = HTTPValidationError>(
 slotId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecordingStatusApiV1RecordingsSlotIdStatusGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecordingStatusApiV1RecordingsSlotIdStatusGetQueryOptions(slotId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



