/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Superadmin Service
 * OpenAPI spec version: 0.1.0
 */
import type { CouponCreateRequestExpiresInHours } from './couponCreateRequestExpiresInHours';
import type { CouponCreateRequestCurrency } from './couponCreateRequestCurrency';
import type { CouponCreateRequestProductId } from './couponCreateRequestProductId';
import type { CouponCreateRequestFreeDaysAllocation } from './couponCreateRequestFreeDaysAllocation';
import type { CouponCreateRequestFreeCreditsAllocation } from './couponCreateRequestFreeCreditsAllocation';

export interface CouponCreateRequest {
  name: string;
  expires_in_hours?: CouponCreateRequestExpiresInHours;
  discount_type: string;
  discount_value: number;
  currency?: CouponCreateRequestCurrency;
  product_id?: CouponCreateRequestProductId;
  free_days_allocation?: CouponCreateRequestFreeDaysAllocation;
  free_credits_allocation?: CouponCreateRequestFreeCreditsAllocation;
}
