/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Superadmin Service
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional label shown on Stripe invoices (e.g. 'Pro Monthly')
 */
export type CreatePriceRequestNickname = string | null;
