/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Superadmin Service
 * OpenAPI spec version: 0.1.0
 */
import type { CreateProductRequestMetadataAnyOf } from './createProductRequestMetadataAnyOf';

export type CreateProductRequestMetadata = CreateProductRequestMetadataAnyOf | null;
