/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Superadmin Service
 * OpenAPI spec version: 0.1.0
 */

export type CreateProductRequestBillingPeriod = 'monthly' | 'yearly' | 'every_3_months' | 'every_6_months' | null;
