/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Superadmin Service
 * OpenAPI spec version: 0.1.0
 */

export interface PermissionRegistryResponse {
  id: string;
  role_name: string;
  permission: string;
  created_at: string;
}
