/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Resume Parsing Service
 * Heavy-lifting AI service for resume extraction and dossier generation
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Candidate Analytics
 */
export const getCandidateAnalyticsApiV1CandidatesAnalyticsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/candidates/analytics`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCandidateAnalyticsApiV1CandidatesAnalyticsGetQueryKey = () => {
    return [
    `/api/v1/candidates/analytics`
    ] as const;
    }

    
export const getGetCandidateAnalyticsApiV1CandidatesAnalyticsGetQueryOptions = <TData = Awaited<ReturnType<typeof getCandidateAnalyticsApiV1CandidatesAnalyticsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidateAnalyticsApiV1CandidatesAnalyticsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateAnalyticsApiV1CandidatesAnalyticsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCandidateAnalyticsApiV1CandidatesAnalyticsGet>>> = ({ signal }) => getCandidateAnalyticsApiV1CandidatesAnalyticsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCandidateAnalyticsApiV1CandidatesAnalyticsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCandidateAnalyticsApiV1CandidatesAnalyticsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCandidateAnalyticsApiV1CandidatesAnalyticsGet>>>
export type GetCandidateAnalyticsApiV1CandidatesAnalyticsGetQueryError = unknown


/**
 * @summary Get Candidate Analytics
 */

export function useGetCandidateAnalyticsApiV1CandidatesAnalyticsGet<TData = Awaited<ReturnType<typeof getCandidateAnalyticsApiV1CandidatesAnalyticsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidateAnalyticsApiV1CandidatesAnalyticsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCandidateAnalyticsApiV1CandidatesAnalyticsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



