/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tenant Service
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignRoleRequest,
  HTTPValidationError,
  IntegrationsConfigRequest,
  SSOConfigRequest,
  SSOConfigUpdateRequest,
  TenantRequest
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Onboard Tenant
 */
export const onboardTenantApiV1TenantsOnboardPost = (
    tenantRequest: TenantRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/onboard`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tenantRequest, signal
    },
      options);
    }
  


export const getOnboardTenantApiV1TenantsOnboardPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardTenantApiV1TenantsOnboardPost>>, TError,{data: TenantRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof onboardTenantApiV1TenantsOnboardPost>>, TError,{data: TenantRequest}, TContext> => {

const mutationKey = ['onboardTenantApiV1TenantsOnboardPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof onboardTenantApiV1TenantsOnboardPost>>, {data: TenantRequest}> = (props) => {
          const {data} = props ?? {};

          return  onboardTenantApiV1TenantsOnboardPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OnboardTenantApiV1TenantsOnboardPostMutationResult = NonNullable<Awaited<ReturnType<typeof onboardTenantApiV1TenantsOnboardPost>>>
    export type OnboardTenantApiV1TenantsOnboardPostMutationBody = TenantRequest
    export type OnboardTenantApiV1TenantsOnboardPostMutationError = HTTPValidationError

    /**
 * @summary Onboard Tenant
 */
export const useOnboardTenantApiV1TenantsOnboardPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardTenantApiV1TenantsOnboardPost>>, TError,{data: TenantRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof onboardTenantApiV1TenantsOnboardPost>>,
        TError,
        {data: TenantRequest},
        TContext
      > => {

      const mutationOptions = getOnboardTenantApiV1TenantsOnboardPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Setup Tenant Sso
 */
export const setupTenantSsoApiV1TenantsSsoSetupPost = (
    sSOConfigRequest: SSOConfigRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/sso/setup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sSOConfigRequest, signal
    },
      options);
    }
  


export const getSetupTenantSsoApiV1TenantsSsoSetupPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setupTenantSsoApiV1TenantsSsoSetupPost>>, TError,{data: SSOConfigRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof setupTenantSsoApiV1TenantsSsoSetupPost>>, TError,{data: SSOConfigRequest}, TContext> => {

const mutationKey = ['setupTenantSsoApiV1TenantsSsoSetupPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setupTenantSsoApiV1TenantsSsoSetupPost>>, {data: SSOConfigRequest}> = (props) => {
          const {data} = props ?? {};

          return  setupTenantSsoApiV1TenantsSsoSetupPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetupTenantSsoApiV1TenantsSsoSetupPostMutationResult = NonNullable<Awaited<ReturnType<typeof setupTenantSsoApiV1TenantsSsoSetupPost>>>
    export type SetupTenantSsoApiV1TenantsSsoSetupPostMutationBody = SSOConfigRequest
    export type SetupTenantSsoApiV1TenantsSsoSetupPostMutationError = HTTPValidationError

    /**
 * @summary Setup Tenant Sso
 */
export const useSetupTenantSsoApiV1TenantsSsoSetupPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setupTenantSsoApiV1TenantsSsoSetupPost>>, TError,{data: SSOConfigRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof setupTenantSsoApiV1TenantsSsoSetupPost>>,
        TError,
        {data: SSOConfigRequest},
        TContext
      > => {

      const mutationOptions = getSetupTenantSsoApiV1TenantsSsoSetupPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get Tenant Sso Status
 */
export const getTenantSsoStatusApiV1TenantsSsoStatusGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/sso/status`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTenantSsoStatusApiV1TenantsSsoStatusGetQueryKey = () => {
    return [
    `/api/v1/tenants/sso/status`
    ] as const;
    }

    
export const getGetTenantSsoStatusApiV1TenantsSsoStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getTenantSsoStatusApiV1TenantsSsoStatusGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantSsoStatusApiV1TenantsSsoStatusGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTenantSsoStatusApiV1TenantsSsoStatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTenantSsoStatusApiV1TenantsSsoStatusGet>>> = ({ signal }) => getTenantSsoStatusApiV1TenantsSsoStatusGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTenantSsoStatusApiV1TenantsSsoStatusGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTenantSsoStatusApiV1TenantsSsoStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTenantSsoStatusApiV1TenantsSsoStatusGet>>>
export type GetTenantSsoStatusApiV1TenantsSsoStatusGetQueryError = unknown


/**
 * @summary Get Tenant Sso Status
 */

export function useGetTenantSsoStatusApiV1TenantsSsoStatusGet<TData = Awaited<ReturnType<typeof getTenantSsoStatusApiV1TenantsSsoStatusGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantSsoStatusApiV1TenantsSsoStatusGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTenantSsoStatusApiV1TenantsSsoStatusGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Tenant Sso Config
 */
export const getTenantSsoConfigApiV1TenantsSsoConfigGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/sso/config`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTenantSsoConfigApiV1TenantsSsoConfigGetQueryKey = () => {
    return [
    `/api/v1/tenants/sso/config`
    ] as const;
    }

    
export const getGetTenantSsoConfigApiV1TenantsSsoConfigGetQueryOptions = <TData = Awaited<ReturnType<typeof getTenantSsoConfigApiV1TenantsSsoConfigGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantSsoConfigApiV1TenantsSsoConfigGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTenantSsoConfigApiV1TenantsSsoConfigGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTenantSsoConfigApiV1TenantsSsoConfigGet>>> = ({ signal }) => getTenantSsoConfigApiV1TenantsSsoConfigGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTenantSsoConfigApiV1TenantsSsoConfigGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTenantSsoConfigApiV1TenantsSsoConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTenantSsoConfigApiV1TenantsSsoConfigGet>>>
export type GetTenantSsoConfigApiV1TenantsSsoConfigGetQueryError = unknown


/**
 * @summary Get Tenant Sso Config
 */

export function useGetTenantSsoConfigApiV1TenantsSsoConfigGet<TData = Awaited<ReturnType<typeof getTenantSsoConfigApiV1TenantsSsoConfigGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantSsoConfigApiV1TenantsSsoConfigGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTenantSsoConfigApiV1TenantsSsoConfigGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update Tenant Sso Config
 */
export const updateTenantSsoConfigApiV1TenantsSsoConfigPut = (
    sSOConfigUpdateRequest: SSOConfigUpdateRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/sso/config`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: sSOConfigUpdateRequest
    },
      options);
    }
  


export const getUpdateTenantSsoConfigApiV1TenantsSsoConfigPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTenantSsoConfigApiV1TenantsSsoConfigPut>>, TError,{data: SSOConfigUpdateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTenantSsoConfigApiV1TenantsSsoConfigPut>>, TError,{data: SSOConfigUpdateRequest}, TContext> => {

const mutationKey = ['updateTenantSsoConfigApiV1TenantsSsoConfigPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTenantSsoConfigApiV1TenantsSsoConfigPut>>, {data: SSOConfigUpdateRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateTenantSsoConfigApiV1TenantsSsoConfigPut(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTenantSsoConfigApiV1TenantsSsoConfigPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateTenantSsoConfigApiV1TenantsSsoConfigPut>>>
    export type UpdateTenantSsoConfigApiV1TenantsSsoConfigPutMutationBody = SSOConfigUpdateRequest
    export type UpdateTenantSsoConfigApiV1TenantsSsoConfigPutMutationError = HTTPValidationError

    /**
 * @summary Update Tenant Sso Config
 */
export const useUpdateTenantSsoConfigApiV1TenantsSsoConfigPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTenantSsoConfigApiV1TenantsSsoConfigPut>>, TError,{data: SSOConfigUpdateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateTenantSsoConfigApiV1TenantsSsoConfigPut>>,
        TError,
        {data: SSOConfigUpdateRequest},
        TContext
      > => {

      const mutationOptions = getUpdateTenantSsoConfigApiV1TenantsSsoConfigPutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Returns the current GitHub PAT configuration and rate limit status for the tenant.
Does not return the actual token string.
 * @summary Get Tenant Github Pat
 */
export const getTenantGithubPatApiV1TenantsIntegrationsGithubGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/integrations/github`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTenantGithubPatApiV1TenantsIntegrationsGithubGetQueryKey = () => {
    return [
    `/api/v1/tenants/integrations/github`
    ] as const;
    }

    
export const getGetTenantGithubPatApiV1TenantsIntegrationsGithubGetQueryOptions = <TData = Awaited<ReturnType<typeof getTenantGithubPatApiV1TenantsIntegrationsGithubGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantGithubPatApiV1TenantsIntegrationsGithubGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTenantGithubPatApiV1TenantsIntegrationsGithubGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTenantGithubPatApiV1TenantsIntegrationsGithubGet>>> = ({ signal }) => getTenantGithubPatApiV1TenantsIntegrationsGithubGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTenantGithubPatApiV1TenantsIntegrationsGithubGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTenantGithubPatApiV1TenantsIntegrationsGithubGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTenantGithubPatApiV1TenantsIntegrationsGithubGet>>>
export type GetTenantGithubPatApiV1TenantsIntegrationsGithubGetQueryError = unknown


/**
 * @summary Get Tenant Github Pat
 */

export function useGetTenantGithubPatApiV1TenantsIntegrationsGithubGet<TData = Awaited<ReturnType<typeof getTenantGithubPatApiV1TenantsIntegrationsGithubGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantGithubPatApiV1TenantsIntegrationsGithubGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTenantGithubPatApiV1TenantsIntegrationsGithubGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update Tenant Github Pat
 */
export const updateTenantGithubPatApiV1TenantsIntegrationsGithubPut = (
    integrationsConfigRequest: IntegrationsConfigRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/integrations/github`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: integrationsConfigRequest
    },
      options);
    }
  


export const getUpdateTenantGithubPatApiV1TenantsIntegrationsGithubPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTenantGithubPatApiV1TenantsIntegrationsGithubPut>>, TError,{data: IntegrationsConfigRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTenantGithubPatApiV1TenantsIntegrationsGithubPut>>, TError,{data: IntegrationsConfigRequest}, TContext> => {

const mutationKey = ['updateTenantGithubPatApiV1TenantsIntegrationsGithubPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTenantGithubPatApiV1TenantsIntegrationsGithubPut>>, {data: IntegrationsConfigRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateTenantGithubPatApiV1TenantsIntegrationsGithubPut(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTenantGithubPatApiV1TenantsIntegrationsGithubPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateTenantGithubPatApiV1TenantsIntegrationsGithubPut>>>
    export type UpdateTenantGithubPatApiV1TenantsIntegrationsGithubPutMutationBody = IntegrationsConfigRequest
    export type UpdateTenantGithubPatApiV1TenantsIntegrationsGithubPutMutationError = HTTPValidationError

    /**
 * @summary Update Tenant Github Pat
 */
export const useUpdateTenantGithubPatApiV1TenantsIntegrationsGithubPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTenantGithubPatApiV1TenantsIntegrationsGithubPut>>, TError,{data: IntegrationsConfigRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateTenantGithubPatApiV1TenantsIntegrationsGithubPut>>,
        TError,
        {data: IntegrationsConfigRequest},
        TContext
      > => {

      const mutationOptions = getUpdateTenantGithubPatApiV1TenantsIntegrationsGithubPutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Assign one or more roles to a user within the caller's tenant.
Only accessible by tenant-admin. Prevents privilege escalation by
restricting which roles can be assigned to the _ASSIGNABLE_ROLES set.
A tenant-admin can never grant another user the tenant-admin role.
 * @summary Assign Role To User
 */
export const assignRoleToUserApiV1TenantsUsersUserIdRolesPost = (
    userId: string,
    assignRoleRequest: AssignRoleRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/users/${userId}/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: assignRoleRequest, signal
    },
      options);
    }
  


export const getAssignRoleToUserApiV1TenantsUsersUserIdRolesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUserApiV1TenantsUsersUserIdRolesPost>>, TError,{userId: string;data: AssignRoleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUserApiV1TenantsUsersUserIdRolesPost>>, TError,{userId: string;data: AssignRoleRequest}, TContext> => {

const mutationKey = ['assignRoleToUserApiV1TenantsUsersUserIdRolesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignRoleToUserApiV1TenantsUsersUserIdRolesPost>>, {userId: string;data: AssignRoleRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  assignRoleToUserApiV1TenantsUsersUserIdRolesPost(userId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AssignRoleToUserApiV1TenantsUsersUserIdRolesPostMutationResult = NonNullable<Awaited<ReturnType<typeof assignRoleToUserApiV1TenantsUsersUserIdRolesPost>>>
    export type AssignRoleToUserApiV1TenantsUsersUserIdRolesPostMutationBody = AssignRoleRequest
    export type AssignRoleToUserApiV1TenantsUsersUserIdRolesPostMutationError = HTTPValidationError

    /**
 * @summary Assign Role To User
 */
export const useAssignRoleToUserApiV1TenantsUsersUserIdRolesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRoleToUserApiV1TenantsUsersUserIdRolesPost>>, TError,{userId: string;data: AssignRoleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof assignRoleToUserApiV1TenantsUsersUserIdRolesPost>>,
        TError,
        {userId: string;data: AssignRoleRequest},
        TContext
      > => {

      const mutationOptions = getAssignRoleToUserApiV1TenantsUsersUserIdRolesPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get all roles currently assigned to a user within this tenant.
Returns which Keycloak groups (roles) the user is a member of.
 * @summary Get User Roles
 */
export const getUserRolesApiV1TenantsUsersUserIdRolesGet = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/users/${userId}/roles`, method: 'GET', signal
    },
      options);
    }
  



export const getGetUserRolesApiV1TenantsUsersUserIdRolesGetQueryKey = (userId?: string,) => {
    return [
    `/api/v1/tenants/users/${userId}/roles`
    ] as const;
    }

    
export const getGetUserRolesApiV1TenantsUsersUserIdRolesGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserRolesApiV1TenantsUsersUserIdRolesGet>>, TError = HTTPValidationError>(userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserRolesApiV1TenantsUsersUserIdRolesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserRolesApiV1TenantsUsersUserIdRolesGetQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserRolesApiV1TenantsUsersUserIdRolesGet>>> = ({ signal }) => getUserRolesApiV1TenantsUsersUserIdRolesGet(userId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserRolesApiV1TenantsUsersUserIdRolesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserRolesApiV1TenantsUsersUserIdRolesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserRolesApiV1TenantsUsersUserIdRolesGet>>>
export type GetUserRolesApiV1TenantsUsersUserIdRolesGetQueryError = HTTPValidationError


/**
 * @summary Get User Roles
 */

export function useGetUserRolesApiV1TenantsUsersUserIdRolesGet<TData = Awaited<ReturnType<typeof getUserRolesApiV1TenantsUsersUserIdRolesGet>>, TError = HTTPValidationError>(
 userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserRolesApiV1TenantsUsersUserIdRolesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserRolesApiV1TenantsUsersUserIdRolesGetQueryOptions(userId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * List all roles available for this tenant.
Returns the pre-defined role names that can be assigned to users.
Roles are automatically provisioned as Keycloak subgroups when the
tenant is onboarded — no manual Keycloak UI work required.
 * @summary List Available Roles
 */
export const listAvailableRolesApiV1TenantsRolesGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/roles`, method: 'GET', signal
    },
      options);
    }
  



export const getListAvailableRolesApiV1TenantsRolesGetQueryKey = () => {
    return [
    `/api/v1/tenants/roles`
    ] as const;
    }

    
export const getListAvailableRolesApiV1TenantsRolesGetQueryOptions = <TData = Awaited<ReturnType<typeof listAvailableRolesApiV1TenantsRolesGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAvailableRolesApiV1TenantsRolesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAvailableRolesApiV1TenantsRolesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAvailableRolesApiV1TenantsRolesGet>>> = ({ signal }) => listAvailableRolesApiV1TenantsRolesGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAvailableRolesApiV1TenantsRolesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAvailableRolesApiV1TenantsRolesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAvailableRolesApiV1TenantsRolesGet>>>
export type ListAvailableRolesApiV1TenantsRolesGetQueryError = unknown


/**
 * @summary List Available Roles
 */

export function useListAvailableRolesApiV1TenantsRolesGet<TData = Awaited<ReturnType<typeof listAvailableRolesApiV1TenantsRolesGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAvailableRolesApiV1TenantsRolesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAvailableRolesApiV1TenantsRolesGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Remove a specific role from a user within the caller's tenant.
Only accessible by tenant-admin.
Cannot remove the 'tenant-admin' role (to prevent tenant lockout).
 * @summary Remove Role From User
 */
export const removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete = (
    userId: string,
    roleName: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/users/${userId}/roles/${roleName}`, method: 'DELETE'
    },
      options);
    }
  


export const getRemoveRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete>>, TError,{userId: string;roleName: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete>>, TError,{userId: string;roleName: string}, TContext> => {

const mutationKey = ['removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete>>, {userId: string;roleName: string}> = (props) => {
          const {userId,roleName} = props ?? {};

          return  removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete(userId,roleName,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete>>>
    
    export type RemoveRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDeleteMutationError = HTTPValidationError

    /**
 * @summary Remove Role From User
 */
export const useRemoveRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete>>, TError,{userId: string;roleName: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof removeRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDelete>>,
        TError,
        {userId: string;roleName: string},
        TContext
      > => {

      const mutationOptions = getRemoveRoleFromUserApiV1TenantsUsersUserIdRolesRoleNameDeleteMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Idempotently (re)create the Keycloak group hierarchy for this tenant.

This is needed for tenants that were onboarded before the group-creation
step was added to the onboarding flow, or where the group creation failed
silently.  It is safe to call multiple times.

Creates:
  - A parent group named after the tenant_id
  - Sub-groups: tenant-admin, recruiter, employee, viewer
  - Adds the calling user to the tenant-admin sub-group
 * @summary Repair Tenant Groups
 */
export const repairTenantGroupsApiV1TenantsRepairGroupsPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/tenants/repair-groups`, method: 'POST', signal
    },
      options);
    }
  


export const getRepairTenantGroupsApiV1TenantsRepairGroupsPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof repairTenantGroupsApiV1TenantsRepairGroupsPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof repairTenantGroupsApiV1TenantsRepairGroupsPost>>, TError,void, TContext> => {

const mutationKey = ['repairTenantGroupsApiV1TenantsRepairGroupsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof repairTenantGroupsApiV1TenantsRepairGroupsPost>>, void> = () => {
          

          return  repairTenantGroupsApiV1TenantsRepairGroupsPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RepairTenantGroupsApiV1TenantsRepairGroupsPostMutationResult = NonNullable<Awaited<ReturnType<typeof repairTenantGroupsApiV1TenantsRepairGroupsPost>>>
    
    export type RepairTenantGroupsApiV1TenantsRepairGroupsPostMutationError = unknown

    /**
 * @summary Repair Tenant Groups
 */
export const useRepairTenantGroupsApiV1TenantsRepairGroupsPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof repairTenantGroupsApiV1TenantsRepairGroupsPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof repairTenantGroupsApiV1TenantsRepairGroupsPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getRepairTenantGroupsApiV1TenantsRepairGroupsPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    