/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Employee Service
 * OpenAPI spec version: 0.1.0
 */

/**
 * Delivery email address (optional). Required for non-gmail users. Must be gmail.com.
 */
export type BulkEmployeeEntryContactEmail = string | null;
