/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Employee Service
 * OpenAPI spec version: 0.1.0
 */

export interface BulkAssignRoleRequest {
  employee_ids: string[];
  new_role: string;
}
