/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Employee Service
 * OpenAPI spec version: 0.1.0
 */

export type ListEmployeesEmployeesGetParams = {
skip?: number;
limit?: number;
status?: string;
};
