/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Orchestrator Service
 * Saga State Machine & Billing Coordinator
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetParams
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Manually trigger a step completion for local testing when Service Bus
is not available. Simulates what would happen when a domain service
publishes a reply event.
 * @summary Simulate Step Result
 */
export const simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/api/v1/internal/orchestrator/simulate-step-result`, method: 'POST', signal
    },
      options);
    }
  


export const getSimulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost>>, TError,void, TContext> => {

const mutationKey = ['simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost>>, void> = () => {
          

          return  simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SimulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPostMutationResult = NonNullable<Awaited<ReturnType<typeof simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost>>>
    
    export type SimulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPostMutationError = unknown

    /**
 * @summary Simulate Step Result
 */
export const useSimulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof simulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getSimulateStepResultInternalApiV1InternalOrchestratorSimulateStepResultPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * List recent workflows (debug/admin).
 * @summary List Workflows
 */
export const listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet = (
    params?: ListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/api/v1/internal/orchestrator/workflows`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetQueryKey = (params?: ListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetParams,) => {
    return [
    `/internal/api/v1/internal/orchestrator/workflows`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetQueryOptions = <TData = Awaited<ReturnType<typeof listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet>>, TError = HTTPValidationError>(params?: ListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet>>> = ({ signal }) => listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet>>>
export type ListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetQueryError = HTTPValidationError


/**
 * @summary List Workflows
 */

export function useListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet<TData = Awaited<ReturnType<typeof listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet>>, TError = HTTPValidationError>(
 params?: ListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsInternalApiV1InternalOrchestratorWorkflowsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListWorkflowsInternalApiV1InternalOrchestratorWorkflowsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



