/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Auth Service
 * OpenAPI spec version: 0.1.0
 */

export interface CandidateGoogleCallbackRequest {
  code: string;
  redirect_uri: string;
}
