/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Orchestrator Service
 * Saga State Machine & Billing Coordinator
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListWorkflowsAliasApiV1OrchestatorWorkflowsGetParams,
  ListWorkflowsAliasApiV1OrchestratorWorkflowsGetParams
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Workflows Alias
 */
export const listWorkflowsAliasApiV1OrchestatorWorkflowsGet = (
    params?: ListWorkflowsAliasApiV1OrchestatorWorkflowsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/orchestator/workflows`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListWorkflowsAliasApiV1OrchestatorWorkflowsGetQueryKey = (params?: ListWorkflowsAliasApiV1OrchestatorWorkflowsGetParams,) => {
    return [
    `/api/v1/orchestator/workflows`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListWorkflowsAliasApiV1OrchestatorWorkflowsGetQueryOptions = <TData = Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestatorWorkflowsGet>>, TError = HTTPValidationError>(params?: ListWorkflowsAliasApiV1OrchestatorWorkflowsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestatorWorkflowsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkflowsAliasApiV1OrchestatorWorkflowsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestatorWorkflowsGet>>> = ({ signal }) => listWorkflowsAliasApiV1OrchestatorWorkflowsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestatorWorkflowsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListWorkflowsAliasApiV1OrchestatorWorkflowsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestatorWorkflowsGet>>>
export type ListWorkflowsAliasApiV1OrchestatorWorkflowsGetQueryError = HTTPValidationError


/**
 * @summary List Workflows Alias
 */

export function useListWorkflowsAliasApiV1OrchestatorWorkflowsGet<TData = Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestatorWorkflowsGet>>, TError = HTTPValidationError>(
 params?: ListWorkflowsAliasApiV1OrchestatorWorkflowsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestatorWorkflowsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListWorkflowsAliasApiV1OrchestatorWorkflowsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary List Workflows Alias
 */
export const listWorkflowsAliasApiV1OrchestratorWorkflowsGet = (
    params?: ListWorkflowsAliasApiV1OrchestratorWorkflowsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/orchestrator/workflows`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListWorkflowsAliasApiV1OrchestratorWorkflowsGetQueryKey = (params?: ListWorkflowsAliasApiV1OrchestratorWorkflowsGetParams,) => {
    return [
    `/api/v1/orchestrator/workflows`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListWorkflowsAliasApiV1OrchestratorWorkflowsGetQueryOptions = <TData = Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestratorWorkflowsGet>>, TError = HTTPValidationError>(params?: ListWorkflowsAliasApiV1OrchestratorWorkflowsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestratorWorkflowsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkflowsAliasApiV1OrchestratorWorkflowsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestratorWorkflowsGet>>> = ({ signal }) => listWorkflowsAliasApiV1OrchestratorWorkflowsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestratorWorkflowsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListWorkflowsAliasApiV1OrchestratorWorkflowsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestratorWorkflowsGet>>>
export type ListWorkflowsAliasApiV1OrchestratorWorkflowsGetQueryError = HTTPValidationError


/**
 * @summary List Workflows Alias
 */

export function useListWorkflowsAliasApiV1OrchestratorWorkflowsGet<TData = Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestratorWorkflowsGet>>, TError = HTTPValidationError>(
 params?: ListWorkflowsAliasApiV1OrchestratorWorkflowsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWorkflowsAliasApiV1OrchestratorWorkflowsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListWorkflowsAliasApiV1OrchestratorWorkflowsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



