/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { CurrentUserTenantId } from './currentUserTenantId';
import type { CurrentUserFirstName } from './currentUserFirstName';
import type { CurrentUserLastName } from './currentUserLastName';
import type { CurrentUserOrganization } from './currentUserOrganization';

/**
 * Authenticated user context extracted from JWT.

This is the primary user object passed to all route handlers
and contains all necessary information for authorization and
tenant isolation.
 */
export interface CurrentUser {
  user_id: string;
  email: string;
  roles: string[];
  tenant_id?: CurrentUserTenantId;
  first_name?: CurrentUserFirstName;
  last_name?: CurrentUserLastName;
  organization?: CurrentUserOrganization;
}
