/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { CurrentUserOrganizationAnyOf } from './currentUserOrganizationAnyOf';

export type CurrentUserOrganization = CurrentUserOrganizationAnyOf | null;
