/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { DetailedHealthResponseServices } from './detailedHealthResponseServices';

/**
 * Detailed health check with service status.
 */
export interface DetailedHealthResponse {
  status: string;
  timestamp: string;
  version: string;
  environment: string;
  services: DetailedHealthResponseServices;
}
