/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */
import type { ProviderType } from './providerType';
import type { EmailConfigurationSaveRequestClientId } from './emailConfigurationSaveRequestClientId';
import type { EmailConfigurationSaveRequestMicrosoftTenantId } from './emailConfigurationSaveRequestMicrosoftTenantId';
import type { EmailConfigurationSaveRequestRefreshToken } from './emailConfigurationSaveRequestRefreshToken';
import type { EmailConfigurationSaveRequestSmtpHost } from './emailConfigurationSaveRequestSmtpHost';
import type { EmailConfigurationSaveRequestSmtpPort } from './emailConfigurationSaveRequestSmtpPort';
import type { EmailConfigurationSaveRequestSmtpUsername } from './emailConfigurationSaveRequestSmtpUsername';
import type { EmailConfigurationSaveRequestPassword } from './emailConfigurationSaveRequestPassword';

export interface EmailConfigurationSaveRequest {
  provider_type: ProviderType;
  client_id?: EmailConfigurationSaveRequestClientId;
  microsoft_tenant_id?: EmailConfigurationSaveRequestMicrosoftTenantId;
  refresh_token?: EmailConfigurationSaveRequestRefreshToken;
  smtp_host?: EmailConfigurationSaveRequestSmtpHost;
  smtp_port?: EmailConfigurationSaveRequestSmtpPort;
  smtp_username?: EmailConfigurationSaveRequestSmtpUsername;
  password?: EmailConfigurationSaveRequestPassword;
}
