/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */

export type GetNotificationsApiV1NotificationsGetParams = {
/**
 * Filter by status (UNREAD, READ)
 */
status?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
