/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */

export type ProviderType = typeof ProviderType[keyof typeof ProviderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProviderType = {
  Microsoft_Graph: 'Microsoft_Graph',
  Google_OAuth: 'Google_OAuth',
  Custom_SMTP: 'Custom_SMTP',
} as const;
