/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Billing Service
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for creating a Stripe checkout session.
 */
export interface CheckoutRequest {
  /** Stripe Price ID (price_...) for the plan to subscribe to */
  price_id: string;
}
