/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Billing Service
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for recording a redemption.
 */
export interface CouponRedemptionRequest {
  stripe_promo_id: string;
  tenant_id: string;
}
