/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Billing Service
 * OpenAPI spec version: 0.1.0
 */
import type { CouponRequestDiscountType } from './couponRequestDiscountType';
import type { CouponRequestProductId } from './couponRequestProductId';
import type { CouponRequestExpiresInHours } from './couponRequestExpiresInHours';
import type { CouponRequestFreeDaysAllocation } from './couponRequestFreeDaysAllocation';
import type { CouponRequestFreeCreditsAllocation } from './couponRequestFreeCreditsAllocation';

/**
 * Request body for creating a coupon.
 */
export interface CouponRequest {
  name: string;
  discount_type: CouponRequestDiscountType;
  discount_value: number;
  currency?: string;
  product_id?: CouponRequestProductId;
  expires_in_hours?: CouponRequestExpiresInHours;
  free_days_allocation?: CouponRequestFreeDaysAllocation;
  free_credits_allocation?: CouponRequestFreeCreditsAllocation;
}
