/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Billing Service
 * OpenAPI spec version: 0.1.0
 */
import type { CreditLedgerResponse } from './creditLedgerResponse';

/**
 * Paginated response for credit ledger history.
 */
export interface CreditLedgerPaginatedResponse {
  items: CreditLedgerResponse[];
  total: number;
}
