/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Billing Service
 * OpenAPI spec version: 0.1.0
 */
import type { CreditLedgerResponseReferenceId } from './creditLedgerResponseReferenceId';

/**
 * Response model for a credit ledger entry (transaction history).
 */
export interface CreditLedgerResponse {
  id: string;
  tenant_id: string;
  transaction_type: string;
  amount: number;
  reference_id: CreditLedgerResponseReferenceId;
  created_at: string;
}
