/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Billing Service
 * OpenAPI spec version: 0.1.0
 */

export type GetCreditHistoryApiV1BillingCreditsHistoryGetParams = {
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
