/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Media Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Receive and process LiveKit webhook events.

Handles:
  - egress_started: Update recording status to RECORDING
  - egress_updated: Update recording progress
  - egress_ended: Update recording to COMPLETED with metadata
  
All handling is idempotent — safe to retry.
 * @summary Handle Livekit Webhook
 */
export const handleLivekitWebhookApiV1WebhooksLivekitPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/webhooks/livekit`, method: 'POST', signal
    },
      options);
    }
  


export const getHandleLivekitWebhookApiV1WebhooksLivekitPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleLivekitWebhookApiV1WebhooksLivekitPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof handleLivekitWebhookApiV1WebhooksLivekitPost>>, TError,void, TContext> => {

const mutationKey = ['handleLivekitWebhookApiV1WebhooksLivekitPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof handleLivekitWebhookApiV1WebhooksLivekitPost>>, void> = () => {
          

          return  handleLivekitWebhookApiV1WebhooksLivekitPost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type HandleLivekitWebhookApiV1WebhooksLivekitPostMutationResult = NonNullable<Awaited<ReturnType<typeof handleLivekitWebhookApiV1WebhooksLivekitPost>>>
    
    export type HandleLivekitWebhookApiV1WebhooksLivekitPostMutationError = unknown

    /**
 * @summary Handle Livekit Webhook
 */
export const useHandleLivekitWebhookApiV1WebhooksLivekitPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof handleLivekitWebhookApiV1WebhooksLivekitPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof handleLivekitWebhookApiV1WebhooksLivekitPost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getHandleLivekitWebhookApiV1WebhooksLivekitPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    