/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Candidate Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Internal endpoint to trigger database provisioning for a tenant in Candidate service.
This is called by the tenant-service during onboarding.
 * @summary Provision Tenant
 */
export const provisionTenantInternalCandidatesProvisionTenantIdPost = (
    tenantId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/candidates/provision/${tenantId}`, method: 'POST', signal
    },
      options);
    }
  


export const getProvisionTenantInternalCandidatesProvisionTenantIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof provisionTenantInternalCandidatesProvisionTenantIdPost>>, TError,{tenantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof provisionTenantInternalCandidatesProvisionTenantIdPost>>, TError,{tenantId: string}, TContext> => {

const mutationKey = ['provisionTenantInternalCandidatesProvisionTenantIdPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof provisionTenantInternalCandidatesProvisionTenantIdPost>>, {tenantId: string}> = (props) => {
          const {tenantId} = props ?? {};

          return  provisionTenantInternalCandidatesProvisionTenantIdPost(tenantId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProvisionTenantInternalCandidatesProvisionTenantIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof provisionTenantInternalCandidatesProvisionTenantIdPost>>>
    
    export type ProvisionTenantInternalCandidatesProvisionTenantIdPostMutationError = HTTPValidationError

    /**
 * @summary Provision Tenant
 */
export const useProvisionTenantInternalCandidatesProvisionTenantIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof provisionTenantInternalCandidatesProvisionTenantIdPost>>, TError,{tenantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof provisionTenantInternalCandidatesProvisionTenantIdPost>>,
        TError,
        {tenantId: string},
        TContext
      > => {

      const mutationOptions = getProvisionTenantInternalCandidatesProvisionTenantIdPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Service-to-service endpoint: rollback a staged resume upload.
Clears staged_resume_blob_url, resets state to IDLE.
Called by job-service when HR rejects a resume update.
 * @summary Rollback Staged Resume
 */
export const rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost = (
    tenantId: string,
    candidateId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/candidates/candidates/${tenantId}/${candidateId}/rollback-staged`, method: 'POST', signal
    },
      options);
    }
  


export const getRollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost>>, TError,{tenantId: string;candidateId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost>>, TError,{tenantId: string;candidateId: number}, TContext> => {

const mutationKey = ['rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost>>, {tenantId: string;candidateId: number}> = (props) => {
          const {tenantId,candidateId} = props ?? {};

          return  rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost(tenantId,candidateId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPostMutationResult = NonNullable<Awaited<ReturnType<typeof rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost>>>
    
    export type RollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPostMutationError = HTTPValidationError

    /**
 * @summary Rollback Staged Resume
 */
export const useRollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost>>, TError,{tenantId: string;candidateId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof rollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPost>>,
        TError,
        {tenantId: string;candidateId: number},
        TContext
      > => {

      const mutationOptions = getRollbackStagedResumeInternalCandidatesCandidatesTenantIdCandidateIdRollbackStagedPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Service-to-service endpoint: query candidate profile state.
Returns state, has_parsed_data, has_staged_upload.
Called by job-service to determine hr_tag on application.
 * @summary Get Candidate State
 */
export const getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet = (
    tenantId: string,
    candidateId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/candidates/candidates/${tenantId}/${candidateId}/state`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGetQueryKey = (tenantId?: string,
    candidateId?: number,) => {
    return [
    `/internal/candidates/candidates/${tenantId}/${candidateId}/state`
    ] as const;
    }

    
export const getGetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGetQueryOptions = <TData = Awaited<ReturnType<typeof getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet>>, TError = HTTPValidationError>(tenantId: string,
    candidateId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGetQueryKey(tenantId,candidateId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet>>> = ({ signal }) => getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet(tenantId,candidateId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(tenantId && candidateId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet>>>
export type GetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGetQueryError = HTTPValidationError


/**
 * @summary Get Candidate State
 */

export function useGetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet<TData = Awaited<ReturnType<typeof getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet>>, TError = HTTPValidationError>(
 tenantId: string,
    candidateId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdStateGetQueryOptions(tenantId,candidateId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Service-to-service endpoint: set candidate state.
Used by job-service for reject-resume (RESUME_REJECTED) and accept-resume-update completion callback.
 * @summary Set Candidate State
 */
export const setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost = (
    tenantId: string,
    candidateId: number,
    setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody: SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/candidates/candidates/${tenantId}/${candidateId}/set-state`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody, signal
    },
      options);
    }
  


export const getSetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost>>, TError,{tenantId: string;candidateId: number;data: SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost>>, TError,{tenantId: string;candidateId: number;data: SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody}, TContext> => {

const mutationKey = ['setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost>>, {tenantId: string;candidateId: number;data: SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody}> = (props) => {
          const {tenantId,candidateId,data} = props ?? {};

          return  setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost(tenantId,candidateId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostMutationResult = NonNullable<Awaited<ReturnType<typeof setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost>>>
    export type SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostMutationBody = SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody
    export type SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostMutationError = HTTPValidationError

    /**
 * @summary Set Candidate State
 */
export const useSetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost>>, TError,{tenantId: string;candidateId: number;data: SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePost>>,
        TError,
        {tenantId: string;candidateId: number;data: SetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody},
        TContext
      > => {

      const mutationOptions = getSetCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Internal endpoint to query candidate-service for the active magic link of an interview.
Called by interview-service during get/list interviews.
 * @summary Get Active Magic Link
 */
export const getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet = (
    tenantId: string,
    interviewId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/candidates/interviews/${tenantId}/${interviewId}/magic-link`, method: 'GET', signal
    },
      options);
    }
  



export const getGetActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGetQueryKey = (tenantId?: string,
    interviewId?: number,) => {
    return [
    `/internal/candidates/interviews/${tenantId}/${interviewId}/magic-link`
    ] as const;
    }

    
export const getGetActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGetQueryOptions = <TData = Awaited<ReturnType<typeof getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet>>, TError = HTTPValidationError>(tenantId: string,
    interviewId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGetQueryKey(tenantId,interviewId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet>>> = ({ signal }) => getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet(tenantId,interviewId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(tenantId && interviewId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGetQueryResult = NonNullable<Awaited<ReturnType<typeof getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet>>>
export type GetActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGetQueryError = HTTPValidationError


/**
 * @summary Get Active Magic Link
 */

export function useGetActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet<TData = Awaited<ReturnType<typeof getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet>>, TError = HTTPValidationError>(
 tenantId: string,
    interviewId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetActiveMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkGetQueryOptions(tenantId,interviewId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Internal endpoint to generate a new magic link token for an interview.
Called by absence_checker.py or other internal services when a rebook/booking magic link is needed.
 * @summary Generate Internal Magic Link
 */
export const generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost = (
    tenantId: string,
    interviewId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/candidates/interviews/${tenantId}/${interviewId}/magic-link`, method: 'POST', signal
    },
      options);
    }
  


export const getGenerateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost>>, TError,{tenantId: string;interviewId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost>>, TError,{tenantId: string;interviewId: number}, TContext> => {

const mutationKey = ['generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost>>, {tenantId: string;interviewId: number}> = (props) => {
          const {tenantId,interviewId} = props ?? {};

          return  generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost(tenantId,interviewId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPostMutationResult = NonNullable<Awaited<ReturnType<typeof generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost>>>
    
    export type GenerateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPostMutationError = HTTPValidationError

    /**
 * @summary Generate Internal Magic Link
 */
export const useGenerateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost>>, TError,{tenantId: string;interviewId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof generateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPost>>,
        TError,
        {tenantId: string;interviewId: number},
        TContext
      > => {

      const mutationOptions = getGenerateInternalMagicLinkInternalCandidatesInterviewsTenantIdInterviewIdMagicLinkPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    