/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkEmployeeInviteRequest,
  BulkEmployeeResponse,
  EmployeeListResponse,
  EmployeeResponse,
  EmployeeStatusResponse,
  ErrorResponse,
  HTTPValidationError,
  ListEmployeesApiV1EmployeesGetParams
} from '.././model';

import { customInstance } from '../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Onboard multiple employees in a single request (up to 100). Validates the caller's JWT and automatically derives the tenant context. Returns per-user results — does not stop the batch on a single failure. Rate limited to 5 requests/minute per IP. Requires admin role.
 * @summary Bulk onboard employees
 */
export const bulkOnboardEmployeesApiV1EmployeesPost = (
    bulkEmployeeInviteRequest: BulkEmployeeInviteRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BulkEmployeeResponse>(
      {url: `/api/v1/employees`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkEmployeeInviteRequest, signal
    },
      options);
    }
  


export const getBulkOnboardEmployeesApiV1EmployeesPostMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkOnboardEmployeesApiV1EmployeesPost>>, TError,{data: BulkEmployeeInviteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof bulkOnboardEmployeesApiV1EmployeesPost>>, TError,{data: BulkEmployeeInviteRequest}, TContext> => {

const mutationKey = ['bulkOnboardEmployeesApiV1EmployeesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkOnboardEmployeesApiV1EmployeesPost>>, {data: BulkEmployeeInviteRequest}> = (props) => {
          const {data} = props ?? {};

          return  bulkOnboardEmployeesApiV1EmployeesPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BulkOnboardEmployeesApiV1EmployeesPostMutationResult = NonNullable<Awaited<ReturnType<typeof bulkOnboardEmployeesApiV1EmployeesPost>>>
    export type BulkOnboardEmployeesApiV1EmployeesPostMutationBody = BulkEmployeeInviteRequest
    export type BulkOnboardEmployeesApiV1EmployeesPostMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Bulk onboard employees
 */
export const useBulkOnboardEmployeesApiV1EmployeesPost = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkOnboardEmployeesApiV1EmployeesPost>>, TError,{data: BulkEmployeeInviteRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof bulkOnboardEmployeesApiV1EmployeesPost>>,
        TError,
        {data: BulkEmployeeInviteRequest},
        TContext
      > => {

      const mutationOptions = getBulkOnboardEmployeesApiV1EmployeesPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Returns a paginated list of all employees in the current tenant workspace. Supports optional filtering by status. Requires admin or recruiter role.
 * @summary List employees
 */
export const listEmployeesApiV1EmployeesGet = (
    params?: ListEmployeesApiV1EmployeesGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EmployeeListResponse>(
      {url: `/api/v1/employees`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListEmployeesApiV1EmployeesGetQueryKey = (params?: ListEmployeesApiV1EmployeesGetParams,) => {
    return [
    `/api/v1/employees`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListEmployeesApiV1EmployeesGetQueryOptions = <TData = Awaited<ReturnType<typeof listEmployeesApiV1EmployeesGet>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError>(params?: ListEmployeesApiV1EmployeesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listEmployeesApiV1EmployeesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEmployeesApiV1EmployeesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEmployeesApiV1EmployeesGet>>> = ({ signal }) => listEmployeesApiV1EmployeesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEmployeesApiV1EmployeesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListEmployeesApiV1EmployeesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listEmployeesApiV1EmployeesGet>>>
export type ListEmployeesApiV1EmployeesGetQueryError = ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError


/**
 * @summary List employees
 */

export function useListEmployeesApiV1EmployeesGet<TData = Awaited<ReturnType<typeof listEmployeesApiV1EmployeesGet>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError>(
 params?: ListEmployeesApiV1EmployeesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listEmployeesApiV1EmployeesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListEmployeesApiV1EmployeesGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Returns details of a specific employee by their ID. Any authenticated user can access.
 * @summary Get employee details
 */
export const getEmployeeApiV1EmployeesEmployeeIdGet = (
    employeeId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EmployeeResponse>(
      {url: `/api/v1/employees/${employeeId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEmployeeApiV1EmployeesEmployeeIdGetQueryKey = (employeeId?: string,) => {
    return [
    `/api/v1/employees/${employeeId}`
    ] as const;
    }

    
export const getGetEmployeeApiV1EmployeesEmployeeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getEmployeeApiV1EmployeesEmployeeIdGet>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError>(employeeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEmployeeApiV1EmployeesEmployeeIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEmployeeApiV1EmployeesEmployeeIdGetQueryKey(employeeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEmployeeApiV1EmployeesEmployeeIdGet>>> = ({ signal }) => getEmployeeApiV1EmployeesEmployeeIdGet(employeeId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(employeeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEmployeeApiV1EmployeesEmployeeIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEmployeeApiV1EmployeesEmployeeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEmployeeApiV1EmployeesEmployeeIdGet>>>
export type GetEmployeeApiV1EmployeesEmployeeIdGetQueryError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError


/**
 * @summary Get employee details
 */

export function useGetEmployeeApiV1EmployeesEmployeeIdGet<TData = Awaited<ReturnType<typeof getEmployeeApiV1EmployeesEmployeeIdGet>>, TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError>(
 employeeId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEmployeeApiV1EmployeesEmployeeIdGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEmployeeApiV1EmployeesEmployeeIdGetQueryOptions(employeeId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Disables an employee's access to the workspace. Also disables their identity in the Identity Provider to prevent SSO login. Requires admin role. Admins cannot disable themselves.
 * @summary Disable employee access
 */
export const disableEmployeeApiV1EmployeesEmployeeIdDisablePatch = (
    employeeId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<EmployeeStatusResponse>(
      {url: `/api/v1/employees/${employeeId}/disable`, method: 'PATCH'
    },
      options);
    }
  


export const getDisableEmployeeApiV1EmployeesEmployeeIdDisablePatchMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableEmployeeApiV1EmployeesEmployeeIdDisablePatch>>, TError,{employeeId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof disableEmployeeApiV1EmployeesEmployeeIdDisablePatch>>, TError,{employeeId: string}, TContext> => {

const mutationKey = ['disableEmployeeApiV1EmployeesEmployeeIdDisablePatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disableEmployeeApiV1EmployeesEmployeeIdDisablePatch>>, {employeeId: string}> = (props) => {
          const {employeeId} = props ?? {};

          return  disableEmployeeApiV1EmployeesEmployeeIdDisablePatch(employeeId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DisableEmployeeApiV1EmployeesEmployeeIdDisablePatchMutationResult = NonNullable<Awaited<ReturnType<typeof disableEmployeeApiV1EmployeesEmployeeIdDisablePatch>>>
    
    export type DisableEmployeeApiV1EmployeesEmployeeIdDisablePatchMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError

    /**
 * @summary Disable employee access
 */
export const useDisableEmployeeApiV1EmployeesEmployeeIdDisablePatch = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableEmployeeApiV1EmployeesEmployeeIdDisablePatch>>, TError,{employeeId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof disableEmployeeApiV1EmployeesEmployeeIdDisablePatch>>,
        TError,
        {employeeId: string},
        TContext
      > => {

      const mutationOptions = getDisableEmployeeApiV1EmployeesEmployeeIdDisablePatchMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Restores a previously disabled employee's access to the workspace. Also enables their identity in the Identity Provider to allow login. Requires admin role.
 * @summary Enable employee access
 */
export const enableEmployeeApiV1EmployeesEmployeeIdEnablePatch = (
    employeeId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<EmployeeStatusResponse>(
      {url: `/api/v1/employees/${employeeId}/enable`, method: 'PATCH'
    },
      options);
    }
  


export const getEnableEmployeeApiV1EmployeesEmployeeIdEnablePatchMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableEmployeeApiV1EmployeesEmployeeIdEnablePatch>>, TError,{employeeId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof enableEmployeeApiV1EmployeesEmployeeIdEnablePatch>>, TError,{employeeId: string}, TContext> => {

const mutationKey = ['enableEmployeeApiV1EmployeesEmployeeIdEnablePatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enableEmployeeApiV1EmployeesEmployeeIdEnablePatch>>, {employeeId: string}> = (props) => {
          const {employeeId} = props ?? {};

          return  enableEmployeeApiV1EmployeesEmployeeIdEnablePatch(employeeId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EnableEmployeeApiV1EmployeesEmployeeIdEnablePatchMutationResult = NonNullable<Awaited<ReturnType<typeof enableEmployeeApiV1EmployeesEmployeeIdEnablePatch>>>
    
    export type EnableEmployeeApiV1EmployeesEmployeeIdEnablePatchMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError

    /**
 * @summary Enable employee access
 */
export const useEnableEmployeeApiV1EmployeesEmployeeIdEnablePatch = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableEmployeeApiV1EmployeesEmployeeIdEnablePatch>>, TError,{employeeId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof enableEmployeeApiV1EmployeesEmployeeIdEnablePatch>>,
        TError,
        {employeeId: string},
        TContext
      > => {

      const mutationOptions = getEnableEmployeeApiV1EmployeesEmployeeIdEnablePatchMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Called by the frontend after an employee successfully logs in for the first time. Transitions the employee's status from 'invited' to 'active'. Requires a valid JWT token.
 * @summary Activate employee post-login
 */
export const activateCurrentEmployeeApiV1EmployeesActivatePost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EmployeeResponse>(
      {url: `/api/v1/employees/activate`, method: 'POST', signal
    },
      options);
    }
  


export const getActivateCurrentEmployeeApiV1EmployeesActivatePostMutationOptions = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateCurrentEmployeeApiV1EmployeesActivatePost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activateCurrentEmployeeApiV1EmployeesActivatePost>>, TError,void, TContext> => {

const mutationKey = ['activateCurrentEmployeeApiV1EmployeesActivatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateCurrentEmployeeApiV1EmployeesActivatePost>>, void> = () => {
          

          return  activateCurrentEmployeeApiV1EmployeesActivatePost(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ActivateCurrentEmployeeApiV1EmployeesActivatePostMutationResult = NonNullable<Awaited<ReturnType<typeof activateCurrentEmployeeApiV1EmployeesActivatePost>>>
    
    export type ActivateCurrentEmployeeApiV1EmployeesActivatePostMutationError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse

    /**
 * @summary Activate employee post-login
 */
export const useActivateCurrentEmployeeApiV1EmployeesActivatePost = <TError = ErrorResponse | ErrorResponse | ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateCurrentEmployeeApiV1EmployeesActivatePost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof activateCurrentEmployeeApiV1EmployeesActivatePost>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getActivateCurrentEmployeeApiV1EmployeesActivatePostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    