/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Orchestrator Service
 * Saga State Machine & Billing Coordinator
 * OpenAPI spec version: 1.0.0
 */

/**
 * POST /orchestrate/confirm — User approves the estimated cost.
 */
export interface ConfirmRequest {
  /** The correlation_id from the execute response */
  correlation_id: string;
}
