/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Orchestrator Service
 * Saga State Machine & Billing Coordinator
 * OpenAPI spec version: 1.0.0
 */
import type { ExecuteRequestPayloadAnyOf } from './executeRequestPayloadAnyOf';

/**
 * Optional domain-specific payload (e.g. job_id, blob paths)
 */
export type ExecuteRequestPayload = ExecuteRequestPayloadAnyOf | null;
