/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Orchestrator Service
 * Saga State Machine & Billing Coordinator
 * OpenAPI spec version: 1.0.0
 */
import type { ExecuteRequestPayload } from './executeRequestPayload';

/**
 * POST /orchestrate/execute — Start a new workflow.
 */
export interface ExecuteRequest {
  /** Name of the pipeline definition, e.g. 'candidate_screening' */
  workflow_name: string;
  /**
   * Number of units to process, e.g. 50 resumes
   * @minimum 1
   */
  quantity: number;
  /** Optional domain-specific payload (e.g. job_id, blob paths) */
  payload?: ExecuteRequestPayload;
}
