/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Orchestrator Service
 * Saga State Machine & Billing Coordinator
 * OpenAPI spec version: 1.0.0
 */
import type { PipelineDefinitionRequestDescription } from './pipelineDefinitionRequestDescription';
import type { StepConfigItem } from './stepConfigItem';

/**
 * POST /pipelines — Create or update a pipeline blueprint.
 */
export interface PipelineDefinitionRequest {
  workflow_name: string;
  description?: PipelineDefinitionRequestDescription;
  steps_config: StepConfigItem[];
}
