/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Candidate Service
 * OpenAPI spec version: 1.0.0
 */

export * from './bookSlotByMagicLinkApiV1CandidatesMagicLinkTokenBookPostBody';
export * from './candidateMeUploadSasApiV1CandidatesMeUploadSasPostBody';
export * from './confirmProcessingApiV1CandidatesCandidateIdConfirmPostBody';
export * from './createCandidateApiV1CandidatesPostBody';
export * from './generateMagicLinkApiV1CandidatesMagicLinkPostBody';
export * from './getDownloadSasApiV1CandidatesCandidateIdDownloadSasGetParams';
export * from './hTTPValidationError';
export * from './processCandidateApiV1CandidatesCandidateIdProcessPostBody';
export * from './processCandidateApiV1CandidatesCandidateIdProcessPostParams';
export * from './saveCandidateMeApiV1CandidatesMePostBody';
export * from './setCandidateStateInternalCandidatesCandidatesTenantIdCandidateIdSetStatePostBody';
export * from './updateCandidateApiV1CandidatesCandidateIdPatchBody';
export * from './updateCandidateMeApiV1CandidatesMePutBody';
export * from './uploadSasApiV1CandidatesUploadSasPostBody';
export * from './validationError';
export * from './validationErrorCtx';
export * from './validationErrorLocItem';