/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Candidate Service
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCandidateMeApiV1CandidatesMePutBody = { [key: string]: unknown };
