/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Job Service
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError
} from '.././model';

import { customInstance } from '../../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Internal endpoint to trigger database provisioning for a tenant in Job service.
This is called by the tenant-service during onboarding.
 * @summary Provision Tenant
 */
export const provisionTenantInternalJobsProvisionTenantIdPost = (
    tenantId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/internal/jobs/provision/${tenantId}`, method: 'POST', signal
    },
      options);
    }
  


export const getProvisionTenantInternalJobsProvisionTenantIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof provisionTenantInternalJobsProvisionTenantIdPost>>, TError,{tenantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof provisionTenantInternalJobsProvisionTenantIdPost>>, TError,{tenantId: string}, TContext> => {

const mutationKey = ['provisionTenantInternalJobsProvisionTenantIdPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof provisionTenantInternalJobsProvisionTenantIdPost>>, {tenantId: string}> = (props) => {
          const {tenantId} = props ?? {};

          return  provisionTenantInternalJobsProvisionTenantIdPost(tenantId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProvisionTenantInternalJobsProvisionTenantIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof provisionTenantInternalJobsProvisionTenantIdPost>>>
    
    export type ProvisionTenantInternalJobsProvisionTenantIdPostMutationError = HTTPValidationError

    /**
 * @summary Provision Tenant
 */
export const useProvisionTenantInternalJobsProvisionTenantIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof provisionTenantInternalJobsProvisionTenantIdPost>>, TError,{tenantId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof provisionTenantInternalJobsProvisionTenantIdPost>>,
        TError,
        {tenantId: string},
        TContext
      > => {

      const mutationOptions = getProvisionTenantInternalJobsProvisionTenantIdPostMutationOptions(options);

      return useMutation(mutationOptions);
    }
    