/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * HRM Multi-Tenant API
 * Production-ready multi-tenant HRM/ATS backend with Keycloak SSO
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EnumValuesResponse,
  GetAllInvoicesSuperadminInvoicesGetParams,
  GetAllPaymentsSuperadminPaymentsGetParams,
  GetAllSubscriptionsSuperadminSubscriptionsGetParams,
  GetAllTenantsSuperadminTenantsGetParams,
  HTTPValidationError,
  PaginatedResponseSubscriptionResponse,
  PaginatedResponseTenantResponse
} from '.././model';

import { customInstance } from '../../axios-setup';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Return all valid enum/filter values used across the superadmin dashboard.
 * @summary Get Enum Values
 */
export const getEnumValuesSuperadminEnumsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EnumValuesResponse>(
      {url: `/superadmin/enums`, method: 'GET', signal
    },
      options);
    }
  



export const getGetEnumValuesSuperadminEnumsGetQueryKey = () => {
    return [
    `/superadmin/enums`
    ] as const;
    }

    
export const getGetEnumValuesSuperadminEnumsGetQueryOptions = <TData = Awaited<ReturnType<typeof getEnumValuesSuperadminEnumsGet>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumValuesSuperadminEnumsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnumValuesSuperadminEnumsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnumValuesSuperadminEnumsGet>>> = ({ signal }) => getEnumValuesSuperadminEnumsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnumValuesSuperadminEnumsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEnumValuesSuperadminEnumsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEnumValuesSuperadminEnumsGet>>>
export type GetEnumValuesSuperadminEnumsGetQueryError = unknown


/**
 * @summary Get Enum Values
 */

export function useGetEnumValuesSuperadminEnumsGet<TData = Awaited<ReturnType<typeof getEnumValuesSuperadminEnumsGet>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEnumValuesSuperadminEnumsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEnumValuesSuperadminEnumsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All Tenants
 */
export const getAllTenantsSuperadminTenantsGet = (
    params?: GetAllTenantsSuperadminTenantsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseTenantResponse>(
      {url: `/superadmin/tenants`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllTenantsSuperadminTenantsGetQueryKey = (params?: GetAllTenantsSuperadminTenantsGetParams,) => {
    return [
    `/superadmin/tenants`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllTenantsSuperadminTenantsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllTenantsSuperadminTenantsGet>>, TError = HTTPValidationError>(params?: GetAllTenantsSuperadminTenantsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllTenantsSuperadminTenantsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTenantsSuperadminTenantsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTenantsSuperadminTenantsGet>>> = ({ signal }) => getAllTenantsSuperadminTenantsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTenantsSuperadminTenantsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllTenantsSuperadminTenantsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTenantsSuperadminTenantsGet>>>
export type GetAllTenantsSuperadminTenantsGetQueryError = HTTPValidationError


/**
 * @summary Get All Tenants
 */

export function useGetAllTenantsSuperadminTenantsGet<TData = Awaited<ReturnType<typeof getAllTenantsSuperadminTenantsGet>>, TError = HTTPValidationError>(
 params?: GetAllTenantsSuperadminTenantsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllTenantsSuperadminTenantsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllTenantsSuperadminTenantsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All Subscriptions
 */
export const getAllSubscriptionsSuperadminSubscriptionsGet = (
    params?: GetAllSubscriptionsSuperadminSubscriptionsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedResponseSubscriptionResponse>(
      {url: `/superadmin/subscriptions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllSubscriptionsSuperadminSubscriptionsGetQueryKey = (params?: GetAllSubscriptionsSuperadminSubscriptionsGetParams,) => {
    return [
    `/superadmin/subscriptions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllSubscriptionsSuperadminSubscriptionsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllSubscriptionsSuperadminSubscriptionsGet>>, TError = HTTPValidationError>(params?: GetAllSubscriptionsSuperadminSubscriptionsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSubscriptionsSuperadminSubscriptionsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSubscriptionsSuperadminSubscriptionsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSubscriptionsSuperadminSubscriptionsGet>>> = ({ signal }) => getAllSubscriptionsSuperadminSubscriptionsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSubscriptionsSuperadminSubscriptionsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllSubscriptionsSuperadminSubscriptionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSubscriptionsSuperadminSubscriptionsGet>>>
export type GetAllSubscriptionsSuperadminSubscriptionsGetQueryError = HTTPValidationError


/**
 * @summary Get All Subscriptions
 */

export function useGetAllSubscriptionsSuperadminSubscriptionsGet<TData = Awaited<ReturnType<typeof getAllSubscriptionsSuperadminSubscriptionsGet>>, TError = HTTPValidationError>(
 params?: GetAllSubscriptionsSuperadminSubscriptionsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSubscriptionsSuperadminSubscriptionsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllSubscriptionsSuperadminSubscriptionsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All Payments
 */
export const getAllPaymentsSuperadminPaymentsGet = (
    params?: GetAllPaymentsSuperadminPaymentsGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/superadmin/payments`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllPaymentsSuperadminPaymentsGetQueryKey = (params?: GetAllPaymentsSuperadminPaymentsGetParams,) => {
    return [
    `/superadmin/payments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllPaymentsSuperadminPaymentsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllPaymentsSuperadminPaymentsGet>>, TError = HTTPValidationError>(params?: GetAllPaymentsSuperadminPaymentsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPaymentsSuperadminPaymentsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllPaymentsSuperadminPaymentsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPaymentsSuperadminPaymentsGet>>> = ({ signal }) => getAllPaymentsSuperadminPaymentsGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllPaymentsSuperadminPaymentsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllPaymentsSuperadminPaymentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPaymentsSuperadminPaymentsGet>>>
export type GetAllPaymentsSuperadminPaymentsGetQueryError = HTTPValidationError


/**
 * @summary Get All Payments
 */

export function useGetAllPaymentsSuperadminPaymentsGet<TData = Awaited<ReturnType<typeof getAllPaymentsSuperadminPaymentsGet>>, TError = HTTPValidationError>(
 params?: GetAllPaymentsSuperadminPaymentsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllPaymentsSuperadminPaymentsGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllPaymentsSuperadminPaymentsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get All Invoices
 */
export const getAllInvoicesSuperadminInvoicesGet = (
    params?: GetAllInvoicesSuperadminInvoicesGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/superadmin/invoices`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetAllInvoicesSuperadminInvoicesGetQueryKey = (params?: GetAllInvoicesSuperadminInvoicesGetParams,) => {
    return [
    `/superadmin/invoices`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllInvoicesSuperadminInvoicesGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllInvoicesSuperadminInvoicesGet>>, TError = HTTPValidationError>(params?: GetAllInvoicesSuperadminInvoicesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllInvoicesSuperadminInvoicesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllInvoicesSuperadminInvoicesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllInvoicesSuperadminInvoicesGet>>> = ({ signal }) => getAllInvoicesSuperadminInvoicesGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllInvoicesSuperadminInvoicesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllInvoicesSuperadminInvoicesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllInvoicesSuperadminInvoicesGet>>>
export type GetAllInvoicesSuperadminInvoicesGetQueryError = HTTPValidationError


/**
 * @summary Get All Invoices
 */

export function useGetAllInvoicesSuperadminInvoicesGet<TData = Awaited<ReturnType<typeof getAllInvoicesSuperadminInvoicesGet>>, TError = HTTPValidationError>(
 params?: GetAllInvoicesSuperadminInvoicesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllInvoicesSuperadminInvoicesGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllInvoicesSuperadminInvoicesGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Tenant Billing
 */
export const getTenantBillingSuperadminTenantTenantIdBillingGet = (
    tenantId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/superadmin/tenant/${tenantId}/billing`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTenantBillingSuperadminTenantTenantIdBillingGetQueryKey = (tenantId?: string,) => {
    return [
    `/superadmin/tenant/${tenantId}/billing`
    ] as const;
    }

    
export const getGetTenantBillingSuperadminTenantTenantIdBillingGetQueryOptions = <TData = Awaited<ReturnType<typeof getTenantBillingSuperadminTenantTenantIdBillingGet>>, TError = HTTPValidationError>(tenantId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantBillingSuperadminTenantTenantIdBillingGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTenantBillingSuperadminTenantTenantIdBillingGetQueryKey(tenantId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTenantBillingSuperadminTenantTenantIdBillingGet>>> = ({ signal }) => getTenantBillingSuperadminTenantTenantIdBillingGet(tenantId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(tenantId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTenantBillingSuperadminTenantTenantIdBillingGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTenantBillingSuperadminTenantTenantIdBillingGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTenantBillingSuperadminTenantTenantIdBillingGet>>>
export type GetTenantBillingSuperadminTenantTenantIdBillingGetQueryError = HTTPValidationError


/**
 * @summary Get Tenant Billing
 */

export function useGetTenantBillingSuperadminTenantTenantIdBillingGet<TData = Awaited<ReturnType<typeof getTenantBillingSuperadminTenantTenantIdBillingGet>>, TError = HTTPValidationError>(
 tenantId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTenantBillingSuperadminTenantTenantIdBillingGet>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTenantBillingSuperadminTenantTenantIdBillingGetQueryOptions(tenantId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



