/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Job Service
 * OpenAPI spec version: 1.0.0
 */

export type UpdateJobRoleBindingsApiV1JobsJobIdRoleBindingsPutBody = { [key: string]: unknown };
