/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduling Service
 * OpenAPI spec version: 1.0.0
 */
import type { AIInterviewDetailsResponseCorrelationId } from './aIInterviewDetailsResponseCorrelationId';
import type { AIInterviewDetailsResponseWindowStart } from './aIInterviewDetailsResponseWindowStart';
import type { AIInterviewDetailsResponseWindowExpiry } from './aIInterviewDetailsResponseWindowExpiry';
import type { AIInterviewDetailsResponseAttemptedAt } from './aIInterviewDetailsResponseAttemptedAt';
import type { AIInterviewDetailsResponseOverallScore } from './aIInterviewDetailsResponseOverallScore';
import type { AIInterviewDetailsResponseRankLabel } from './aIInterviewDetailsResponseRankLabel';
import type { AIInterviewDetailsResponseTopicsAssessed } from './aIInterviewDetailsResponseTopicsAssessed';
import type { AIInterviewDetailsResponseTotalTopics } from './aIInterviewDetailsResponseTotalTopics';
import type { AIInterviewDetailsResponsePlanUrl } from './aIInterviewDetailsResponsePlanUrl';
import type { AIInterviewDetailsResponseTranscriptUrl } from './aIInterviewDetailsResponseTranscriptUrl';
import type { AIInterviewDetailsResponseReportUrl } from './aIInterviewDetailsResponseReportUrl';
import type { AIInterviewDetailsResponseAnalysisUrl } from './aIInterviewDetailsResponseAnalysisUrl';
import type { AIInterviewDetailsResponseRecordingUrl } from './aIInterviewDetailsResponseRecordingUrl';

/**
 * Full details of an AI interview including recording access.
 */
export interface AIInterviewDetailsResponse {
  interview_id: number;
  session_id: string;
  status: string;
  duration_minutes: number;
  candidate_id: number;
  job_id: number;
  correlation_id?: AIInterviewDetailsResponseCorrelationId;
  window_start?: AIInterviewDetailsResponseWindowStart;
  window_expiry?: AIInterviewDetailsResponseWindowExpiry;
  attempted_at?: AIInterviewDetailsResponseAttemptedAt;
  overall_score?: AIInterviewDetailsResponseOverallScore;
  rank_label?: AIInterviewDetailsResponseRankLabel;
  topics_assessed?: AIInterviewDetailsResponseTopicsAssessed;
  total_topics?: AIInterviewDetailsResponseTotalTopics;
  plan_url?: AIInterviewDetailsResponsePlanUrl;
  transcript_url?: AIInterviewDetailsResponseTranscriptUrl;
  report_url?: AIInterviewDetailsResponseReportUrl;
  analysis_url?: AIInterviewDetailsResponseAnalysisUrl;
  recording_url?: AIInterviewDetailsResponseRecordingUrl;
}
