/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduling Service
 * OpenAPI spec version: 1.0.0
 */

export interface ScheduleAIInterviewResponse {
  interview_id: number;
  session_id: string;
  correlation_id: string;
  estimated_credits: number;
  window_start: string;
  window_expiry: string;
  status?: string;
}
