/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Scheduling Service
 * OpenAPI spec version: 1.0.0
 */

export type UpdatePanelMembersApiV1SchedulingInterviewIdPanelMembersPatchBody = { [key: string]: unknown };
